# Generated by Django 6.1.1 on 2026-09-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='leaf', help_text='Emoji or icon identifier', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField()),
                ('delivery_slot', models.CharField(default='Express Delivery: Within 2 Hours', help_text='Selected delivery slot window', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI (Google Pay, PhonePe, Paytm)'), ('CARD', 'Credit / Debit Card'), ('COD', 'Cash on Delivery (COD)')], default='UPI', max_length=50)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Order Confirmed'), ('PACKING', 'Packing at Farm Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text="Short hook, e.g. 'Crisp, sweet, directly from Shimla orchards'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price in ₹ INR', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for strikethrough discount', max_digits=10, null=True)),
                ('unit', models.CharField(default='1 kg', help_text="Unit metric e.g., '1 kg', '500g', 'bunch', 'box'", max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=50)),
                ('freshness_tag', models.CharField(default='Fresh Harvest', help_text="e.g. 'Just Harvested', 'GI Tagged', 'Pesticide Free'", max_length=100)),
                ('is_organic', models.BooleanField(default=True)),
                ('image_url', models.URLField(help_text='High-resolution image URL', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=128)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_unit', models.CharField(default='1 kg', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
