# Generated by Django 6.1.1 on 2026-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='/fruits/apples.jpg', help_text='High-resolution image URL or uploaded image path', max_length=2000),
        ),
    ]
