"""
Management command to seed FreshCart database with realistic Indian organic farm produce.
Usage: python manage.py seed_data
"""

from django.core.management.base import BaseCommand
from decimal import Decimal
from store.models import Category, Product


class Command(BaseCommand):
    help = 'Seeds the database with categories and all 46 fruit produce items with simple naming.'

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding FreshCart database with all fruits..."))

        categories_data = [
            {'name': 'Fresh Fruits', 'slug': 'fruits', 'icon': '🍎', 'display_order': 1},
            {'name': 'Leafy Greens', 'slug': 'greens', 'icon': '🥬', 'display_order': 2},
            {'name': 'Daily Veggies', 'slug': 'veggies', 'icon': '🥕', 'display_order': 3},
        ]

        # Ensure exotic category is removed from DB
        Category.objects.filter(slug='exotic').delete()

        categories_dict = {}
        for cat_data in categories_data:
            category, created = Category.objects.update_or_create(
                slug=cat_data['slug'],
                defaults=cat_data
            )
            categories_dict[cat_data['slug']] = category
            status_text = "Created" if created else "Updated"
            self.stdout.write(f"  {status_text} category: {category.name}")

        # Clean existing products to avoid stale/duplicate names
        Product.objects.all().delete()

        products_data = [
            # === All 46 Fruits with simple naming ===
            {
                'category': categories_dict['fruits'],
                'name': 'Apples',
                'tagline': 'Crisp, naturally sweet orchard-picked red apples',
                'description': 'Crunchy and juicy fresh apples grown in sunny mountain slopes, free from artificial wax.',
                'price': Decimal('180.00'),
                'original_price': Decimal('220.00'),
                'unit': '1 kg (4-5 pcs)',
                'stock_quantity': 50,
                'freshness_tag': 'Orchard Fresh',
                'is_organic': True,
                'image_url': '/fruits/apples.jpg',
                'rating': Decimal('4.9'),
                'review_count': 248,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Apricots',
                'tagline': 'Golden-orange sweet and tangy fresh apricots',
                'description': 'Plump sun-ripened apricots packed with vitamins, dietary fiber, and delicate floral sweetness.',
                'price': Decimal('260.00'),
                'original_price': Decimal('320.00'),
                'unit': '500g box',
                'stock_quantity': 35,
                'freshness_tag': 'Farm Fresh',
                'is_organic': True,
                'image_url': '/fruits/apricots.jpg',
                'rating': Decimal('4.8'),
                'review_count': 112,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Avocados',
                'tagline': 'Creamy, nutty Hass avocados perfect for guacamole & toast',
                'description': 'Rich in heart-healthy natural oils. Buttery smooth texture that mashes effortlessly.',
                'price': Decimal('180.00'),
                'original_price': Decimal('220.00'),
                'unit': '2 pcs (approx 450g)',
                'stock_quantity': 40,
                'freshness_tag': 'Creamy Ripe',
                'is_organic': True,
                'image_url': '/fruits/avacados.jpg',
                'rating': Decimal('4.9'),
                'review_count': 324,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Bananas',
                'tagline': 'Naturally tree-ripened sweet yellow bananas',
                'description': 'Wholesome everyday bananas rich in potassium and energy. Ripened without harmful chemicals.',
                'price': Decimal('60.00'),
                'original_price': Decimal('80.00'),
                'unit': '1 kg (10-12 pcs)',
                'stock_quantity': 80,
                'freshness_tag': 'Tree Ripened',
                'is_organic': True,
                'image_url': '/fruits/bananas.jpg',
                'rating': Decimal('4.8'),
                'review_count': 318,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Blackberries',
                'tagline': 'Juicy, antioxidant-packed sweet wild blackberries',
                'description': 'Deep purple, plump wild berries freshly picked from highland brambles. Wonderful in yogurt or raw.',
                'price': Decimal('180.00'),
                'original_price': Decimal('230.00'),
                'unit': '150g punnet',
                'stock_quantity': 25,
                'freshness_tag': 'Superfood',
                'is_organic': True,
                'image_url': '/fruits/black_berry.jpg',
                'rating': Decimal('4.9'),
                'review_count': 94,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Blackcurrants',
                'tagline': 'Tart-sweet aromatic blackcurrants bursting with flavor',
                'description': 'Glossy dark berries celebrated for rich antioxidants, baking, and refreshing juices.',
                'price': Decimal('200.00'),
                'original_price': Decimal('250.00'),
                'unit': '200g box',
                'stock_quantity': 20,
                'freshness_tag': 'High Vitamin C',
                'is_organic': True,
                'image_url': '/fruits/black_current.jpg',
                'rating': Decimal('4.7'),
                'review_count': 76,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Black Grapes',
                'tagline': 'Crisp, sweet seedless midnight-black grapes',
                'description': 'Naturally sun-sweetened with thin skins and rich anthocyanins. Pre-washed in clean ozonated water.',
                'price': Decimal('90.00'),
                'original_price': Decimal('120.00'),
                'unit': '500g punnet',
                'stock_quantity': 45,
                'freshness_tag': 'Seedless',
                'is_organic': True,
                'image_url': '/fruits/black_grapes.jpg',
                'rating': Decimal('4.9'),
                'review_count': 210,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Blueberries',
                'tagline': 'Plump indigo sweet blueberries with silver bloom',
                'description': 'Pesticide-free cultivated berries. Sweet, juicy, and delicious for morning smoothies and breakfast.',
                'price': Decimal('220.00'),
                'original_price': Decimal('280.00'),
                'unit': '125g punnet',
                'stock_quantity': 30,
                'freshness_tag': 'Antioxidant Rich',
                'is_organic': True,
                'image_url': '/fruits/blue_berries.jpg',
                'rating': Decimal('4.9'),
                'review_count': 142,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Cashew Apples',
                'tagline': 'Fragrant, juicy tropical cashew fruit with exotic aroma',
                'description': 'Unique, vibrant tropical fruit packed with five times more Vitamin C than oranges. Intensely juicy.',
                'price': Decimal('120.00'),
                'original_price': Decimal('160.00'),
                'unit': '500g pack',
                'stock_quantity': 25,
                'freshness_tag': 'Tropical Rare',
                'is_organic': True,
                'image_url': '/fruits/cashewapples.jpg',
                'rating': Decimal('4.6'),
                'review_count': 58,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Cherries',
                'tagline': 'Sweet, ruby-red juicy mountain cherries',
                'description': 'Crisp, glossy cherries handpicked from high elevation orchards. Perfect fresh sweet crunch.',
                'price': Decimal('320.00'),
                'original_price': Decimal('400.00'),
                'unit': '500g box',
                'stock_quantity': 25,
                'freshness_tag': 'Valley Fresh',
                'is_organic': True,
                'image_url': '/fruits/cherries.jpg',
                'rating': Decimal('5.0'),
                'review_count': 156,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Cranberries',
                'tagline': 'Bright red, tart and zesty nutrient-dense cranberries',
                'description': 'Vibrant red berries known for wellness and refreshing tartness. Excellent for juices and sauces.',
                'price': Decimal('210.00'),
                'original_price': Decimal('260.00'),
                'unit': '200g box',
                'stock_quantity': 20,
                'freshness_tag': 'Wellness Superfood',
                'is_organic': True,
                'image_url': '/fruits/cranberries.jpg',
                'rating': Decimal('4.7'),
                'review_count': 82,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Custard Apples',
                'tagline': 'Creamy, sweet sugar-apple pulp with heavenly aroma',
                'description': 'Naturally soft Sitaphal with rich sugary segments. Packed with magnesium, calcium, and vitamin B6.',
                'price': Decimal('130.00'),
                'original_price': Decimal('170.00'),
                'unit': '1 kg (3-4 pcs)',
                'stock_quantity': 35,
                'freshness_tag': 'Honey Sweet',
                'is_organic': True,
                'image_url': '/fruits/custard_apples.jpg',
                'rating': Decimal('4.9'),
                'review_count': 172,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Dragon Fruit',
                'tagline': 'Vibrant fuchsia pitaya with delicate sweetness',
                'description': 'Exotic dragon fruit with jewel-pink exterior and crunchy seed-speckled pulp. Packed with prebiotics.',
                'price': Decimal('110.00'),
                'original_price': Decimal('150.00'),
                'unit': '1 pc (approx 350g)',
                'stock_quantity': 40,
                'freshness_tag': 'Exotic Pick',
                'is_organic': True,
                'image_url': '/fruits/dragonfruits.jpg',
                'rating': Decimal('4.8'),
                'review_count': 195,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Durian',
                'tagline': 'The King of Fruits with rich, golden creamy custard pods',
                'description': 'Distinctive exotic specialty fruit with golden-yellow custard pods possessing rich creamy sweetness.',
                'price': Decimal('750.00'),
                'original_price': Decimal('950.00'),
                'unit': '1 kg',
                'stock_quantity': 15,
                'freshness_tag': 'Exotic King',
                'is_organic': True,
                'image_url': '/fruits/durian.jpg',
                'rating': Decimal('4.7'),
                'review_count': 88,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Figs',
                'tagline': 'Plump fresh purple figs dripping with delicate honey sweetness',
                'description': 'Tender sweet Anjeer freshly plucked from orchards. Superb source of natural calcium and dietary fiber.',
                'price': Decimal('130.00'),
                'original_price': Decimal('170.00'),
                'unit': '500g box',
                'stock_quantity': 25,
                'freshness_tag': 'Tender & Sweet',
                'is_organic': True,
                'image_url': '/fruits/figs.jpg',
                'rating': Decimal('4.9'),
                'review_count': 115,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Gooseberries (Amla)',
                'tagline': 'Wild, immunity-boosting Indian amla rich in Vitamin C',
                'description': 'Crisp, tangy-tart green amla berries traditionally celebrated in Ayurveda for gut health and immunity.',
                'price': Decimal('60.00'),
                'original_price': Decimal('85.00'),
                'unit': '500g pack',
                'stock_quantity': 60,
                'freshness_tag': 'Ayurvedic Amla',
                'is_organic': True,
                'image_url': '/fruits/gooseberries.jpg',
                'rating': Decimal('4.8'),
                'review_count': 164,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Grapefruit',
                'tagline': 'Juicy ruby-red citrus with crisp bittersweet refreshing flavor',
                'description': 'Thick-peeled, vibrant pink citrus segments loaded with lycopene, vitamin C, and revitalizing juice.',
                'price': Decimal('120.00'),
                'original_price': Decimal('150.00'),
                'unit': '2 pcs (approx 600g)',
                'stock_quantity': 35,
                'freshness_tag': 'Ruby Red',
                'is_organic': True,
                'image_url': '/fruits/grape_fruit.jpg',
                'rating': Decimal('4.7'),
                'review_count': 78,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Green Apples',
                'tagline': 'Ultra-crisp, tangy Granny Smith green apples',
                'description': 'Bright emerald skin with tart, crunchy flesh. Excellent for juicing, fresh salads, or crisp snacking.',
                'price': Decimal('210.00'),
                'original_price': Decimal('250.00'),
                'unit': '1 kg (4-5 pcs)',
                'stock_quantity': 40,
                'freshness_tag': 'Crisp Tart',
                'is_organic': True,
                'image_url': '/fruits/green_apples.jpg',
                'rating': Decimal('4.8'),
                'review_count': 134,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Guava',
                'tagline': 'Fragrant, white-fleshed sweet guava with edible skin',
                'description': 'Mild sweet flavor with crunchy edible seeds and pleasant scent. Rich in natural pectin and fiber.',
                'price': Decimal('80.00'),
                'original_price': Decimal('105.00'),
                'unit': '1 kg (4-5 pcs)',
                'stock_quantity': 55,
                'freshness_tag': 'Vitamin C Rich',
                'is_organic': True,
                'image_url': '/fruits/guava.jpg',
                'rating': Decimal('4.7'),
                'review_count': 145,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Jackfruit',
                'tagline': 'Tender raw or sweet ripe tropical jackfruit pods',
                'description': 'Large tropical treasure with aromatic sweet golden segments or nutritious vegetable cooking bulbs.',
                'price': Decimal('90.00'),
                'original_price': Decimal('120.00'),
                'unit': '500g cut pack',
                'stock_quantity': 30,
                'freshness_tag': 'Farm Harvested',
                'is_organic': True,
                'image_url': '/fruits/jackfruit.jpg',
                'rating': Decimal('4.7'),
                'review_count': 92,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Jujube (Ber)',
                'tagline': 'Crisp, sweet and tart native Indian plum berries',
                'description': 'Small crunchy green and red berries with pleasant sweet-sour crispness reminiscent of miniature apples.',
                'price': Decimal('70.00'),
                'original_price': Decimal('95.00'),
                'unit': '500g pack',
                'stock_quantity': 45,
                'freshness_tag': 'Seasonal Ber',
                'is_organic': True,
                'image_url': '/fruits/jujube.jpg',
                'rating': Decimal('4.8'),
                'review_count': 118,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Kiwi',
                'tagline': 'Tangy-sweet bright green kiwis loaded with Vitamin C',
                'description': 'Fuzzy brown skin with radiant emerald flesh and crunchy black seeds. Boosts digestion and energy.',
                'price': Decimal('120.00'),
                'original_price': Decimal('160.00'),
                'unit': '3 pcs pack',
                'stock_quantity': 50,
                'freshness_tag': 'Zesty Fresh',
                'is_organic': True,
                'image_url': '/fruits/kiwi.jpg',
                'rating': Decimal('4.8'),
                'review_count': 168,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Litchi',
                'tagline': 'Floral, translucent sweet pulp bursting with nectar',
                'description': 'Delicate bumpy red rind peeling to reveal fragrant, succulent white pulp with intoxicating sweetness.',
                'price': Decimal('220.00'),
                'original_price': Decimal('280.00'),
                'unit': '1 kg',
                'stock_quantity': 30,
                'freshness_tag': 'Floral Sweet',
                'is_organic': True,
                'image_url': '/fruits/litchi.jpg',
                'rating': Decimal('4.9'),
                'review_count': 240,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Makoy Berries',
                'tagline': 'Dark, sweet traditional Indian wild nightshade berries',
                'description': 'Tiny black-purple berries known in herbal traditions for soothing digestion and rich nutrients.',
                'price': Decimal('90.00'),
                'original_price': Decimal('120.00'),
                'unit': '250g pack',
                'stock_quantity': 20,
                'freshness_tag': 'Wild Herbal',
                'is_organic': True,
                'image_url': '/fruits/makoy.jpg',
                'rating': Decimal('4.6'),
                'review_count': 45,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Rose Apples',
                'tagline': 'Crisp, bell-shaped crunchy rose-scented water apples',
                'description': 'Unusually crisp, thirst-quenching bell fruit with subtle rosewater fragrance and pleasant sweetness.',
                'price': Decimal('150.00'),
                'original_price': Decimal('190.00'),
                'unit': '500g box',
                'stock_quantity': 25,
                'freshness_tag': 'Crisp Water Fruit',
                'is_organic': True,
                'image_url': '/fruits/malay_apple.jpg',
                'rating': Decimal('4.7'),
                'review_count': 62,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Mangoes',
                'tagline': 'Naturally ripened, heavenly sweet king of fruits',
                'description': 'Velvety saffron pulp with an intoxicating floral fragrance. 100% carbide-free and tree-ripened.',
                'price': Decimal('699.00'),
                'original_price': Decimal('899.00'),
                'unit': '6 pcs box',
                'stock_quantity': 35,
                'freshness_tag': 'King of Fruits',
                'is_organic': True,
                'image_url': '/fruits/mangoes.jpg',
                'rating': Decimal('5.0'),
                'review_count': 482,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Mangosteen',
                'tagline': 'The Queen of Fruits with delicate sweet white segments',
                'description': 'Thick purple rind encasing soft, snow-white juicy citrus-peach flavored segments of royalty.',
                'price': Decimal('320.00'),
                'original_price': Decimal('400.00'),
                'unit': '4 pcs (approx 350g)',
                'stock_quantity': 20,
                'freshness_tag': 'Queen of Fruits',
                'is_organic': True,
                'image_url': '/fruits/mangosteen.jpg',
                'rating': Decimal('4.9'),
                'review_count': 108,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Mulberries',
                'tagline': 'Sweet, tender crimson-black Shahtoot mulberries',
                'description': 'Delicate elongated berries bursting with gentle sweet juice. Harvested with utmost care.',
                'price': Decimal('110.00'),
                'original_price': Decimal('145.00'),
                'unit': '200g punnet',
                'stock_quantity': 25,
                'freshness_tag': 'Delicate Shahtoot',
                'is_organic': True,
                'image_url': '/fruits/mulberries.jpg',
                'rating': Decimal('4.8'),
                'review_count': 96,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Muskmelon',
                'tagline': 'Sweet, aromatic netted melon with soft honeyed orange flesh',
                'description': 'Naturally fragrant cantaloupe melon. Ultra hydrating, cooling, and filled with sweet summer juice.',
                'price': Decimal('75.00'),
                'original_price': Decimal('95.00'),
                'unit': '1 pc (1 - 1.2 kg)',
                'stock_quantity': 40,
                'freshness_tag': 'Honey Sweet',
                'is_organic': True,
                'image_url': '/fruits/muskmelon.jpg',
                'rating': Decimal('4.8'),
                'review_count': 178,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Oranges',
                'tagline': 'Juicy, sweet sun-kissed citrus bursting with Vitamin C',
                'description': 'Thin peeled, tender segments full of bright sweet-tart juice. Ideal for refreshing morning juicing.',
                'price': Decimal('110.00'),
                'original_price': Decimal('140.00'),
                'unit': '1 kg (5-6 pcs)',
                'stock_quantity': 60,
                'freshness_tag': 'Farm Picked',
                'is_organic': True,
                'image_url': '/fruits/oranges.jpg',
                'rating': Decimal('4.8'),
                'review_count': 184,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Papaya',
                'tagline': 'Sweet, buttery salmon-orange ripe dessert papaya',
                'description': 'Easy-to-digest tropical fruit rich in papain enzymes and Vitamin A. Smooth sweet flavor.',
                'price': Decimal('65.00'),
                'original_price': Decimal('85.00'),
                'unit': '1 pc (1 - 1.2 kg)',
                'stock_quantity': 50,
                'freshness_tag': 'Enzyme Rich',
                'is_organic': True,
                'image_url': '/fruits/papaya.jpg',
                'rating': Decimal('4.8'),
                'review_count': 210,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Passion Fruit',
                'tagline': 'Aromatic, tangy tropical pulp with crunchy edible seeds',
                'description': 'Wrinkled purple globe containing intensely aromatic golden nectar. Elevates desserts, juices, and bowls.',
                'price': Decimal('160.00'),
                'original_price': Decimal('200.00'),
                'unit': '4 pcs pack',
                'stock_quantity': 25,
                'freshness_tag': 'Tropical Aroma',
                'is_organic': True,
                'image_url': '/fruits/passionfruit.jpg',
                'rating': Decimal('4.9'),
                'review_count': 88,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Peaches',
                'tagline': 'Velvety, fragrant sweet yellow mountain peaches',
                'description': 'Soft fuzzy skin with succulent golden flesh dripping with sweet juice. Plucked at peak ripeness.',
                'price': Decimal('190.00'),
                'original_price': Decimal('240.00'),
                'unit': '500g box',
                'stock_quantity': 30,
                'freshness_tag': 'Hill Sourced',
                'is_organic': True,
                'image_url': '/fruits/peaches.jpg',
                'rating': Decimal('4.8'),
                'review_count': 120,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Pears',
                'tagline': 'Crisp, refreshing sweet green Nashpati pears',
                'description': 'Firm green skin with crisp, grainy, juicy white flesh that refreshes the palate.',
                'price': Decimal('140.00'),
                'original_price': Decimal('180.00'),
                'unit': '1 kg (4-5 pcs)',
                'stock_quantity': 45,
                'freshness_tag': 'Crisp Pear',
                'is_organic': True,
                'image_url': '/fruits/pears.jpg',
                'rating': Decimal('4.7'),
                'review_count': 114,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Persimmons',
                'tagline': 'Glossy orange, honey-sweet Japani phal persimmons',
                'description': 'Smooth jelly-like honeyed sweetness when fully ripe. A rare winter mountain orchard specialty.',
                'price': Decimal('180.00'),
                'original_price': Decimal('230.00'),
                'unit': '500g box',
                'stock_quantity': 25,
                'freshness_tag': 'Orchard Rare',
                'is_organic': True,
                'image_url': '/fruits/persimmon.jpg',
                'rating': Decimal('4.8'),
                'review_count': 72,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Pineapple',
                'tagline': 'Golden, sweet and fragrant Queen pineapple',
                'description': 'Tropical sweet crown fruit with juicy golden flesh and tender core. Naturally rich in bromelain.',
                'price': Decimal('95.00'),
                'original_price': Decimal('130.00'),
                'unit': '1 pc (approx 800g)',
                'stock_quantity': 35,
                'freshness_tag': 'Sweet Queen',
                'is_organic': True,
                'image_url': '/fruits/pineapple.jpg',
                'rating': Decimal('4.9'),
                'review_count': 188,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Plums',
                'tagline': 'Succulent deep red sweet and tart fresh plums',
                'description': 'Smooth glossy red skin with ruby-colored juicy pulp. High in antioxidants and vitamins.',
                'price': Decimal('160.00'),
                'original_price': Decimal('200.00'),
                'unit': '500g box',
                'stock_quantity': 35,
                'freshness_tag': 'Juicy Plums',
                'is_organic': True,
                'image_url': '/fruits/plums.jpg',
                'rating': Decimal('4.8'),
                'review_count': 130,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Pomelo',
                'tagline': 'Giant sweet citrus with mild, refreshing pink vesicles',
                'description': 'The largest citrus fruit. Sweet, mild flavor without bitter aftertaste. Very easy to peel and savor.',
                'price': Decimal('130.00'),
                'original_price': Decimal('170.00'),
                'unit': '1 pc (approx 1 kg)',
                'stock_quantity': 25,
                'freshness_tag': 'Giant Citrus',
                'is_organic': True,
                'image_url': '/fruits/pomelo.jpg',
                'rating': Decimal('4.7'),
                'review_count': 64,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Pomegranates',
                'tagline': 'Ruby-red juicy Bhagwa arils brimming with antioxidants',
                'description': 'Glossy crimson pearls dripping with sweet nectar. Hand-selected for maximum sweetness and soft seeds.',
                'price': Decimal('180.00'),
                'original_price': Decimal('230.00'),
                'unit': '1 kg (3-4 pcs)',
                'stock_quantity': 50,
                'freshness_tag': 'Bhagwa Ruby',
                'is_organic': True,
                'image_url': '/fruits/pomogranate.jpg',
                'rating': Decimal('4.9'),
                'review_count': 260,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Raspberries',
                'tagline': 'Delicate, ruby-red tart-sweet fresh raspberries',
                'description': 'Melt-in-mouth berries packed with fiber, vitamin C, and radiant taste. Sourced in cold containers.',
                'price': Decimal('260.00'),
                'original_price': Decimal('320.00'),
                'unit': '150g punnet',
                'stock_quantity': 20,
                'freshness_tag': 'Cold-Chain',
                'is_organic': True,
                'image_url': '/fruits/raspberries.jpg',
                'rating': Decimal('4.9'),
                'review_count': 110,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Sapota (Chiku)',
                'tagline': 'Caramel-sweet brown sapota with soft grainy texture',
                'description': 'Rich, honeyed sweetness reminiscent of brown sugar and pears. Naturally high in calcium and energy.',
                'price': Decimal('70.00'),
                'original_price': Decimal('95.00'),
                'unit': '1 kg (8-10 pcs)',
                'stock_quantity': 60,
                'freshness_tag': 'Caramel Sweet',
                'is_organic': True,
                'image_url': '/fruits/sapota.jpg',
                'rating': Decimal('4.8'),
                'review_count': 189,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Star Fruit',
                'tagline': 'Crisp, star-shaped yellow carambola with citrus sweetness',
                'description': 'Beautiful star slices that are juicy, tangy, and thirst-quenching. Ideal for fruit platters and snacks.',
                'price': Decimal('60.00'),
                'original_price': Decimal('85.00'),
                'unit': '250g pack (3-4 pcs)',
                'stock_quantity': 30,
                'freshness_tag': 'Crisp Carambola',
                'is_organic': True,
                'image_url': '/fruits/star_fruit.jpg',
                'rating': Decimal('4.7'),
                'review_count': 82,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Strawberries',
                'tagline': 'Plump, fragrant ruby strawberries picked at dawn',
                'description': 'Misty red soil strawberries packed in protective punnets. Unbruised, aromatic, and sweet.',
                'price': Decimal('160.00'),
                'original_price': Decimal('210.00'),
                'unit': '250g box',
                'stock_quantity': 35,
                'freshness_tag': 'Cold-Chain Express',
                'is_organic': True,
                'image_url': '/fruits/strawberries.jpg',
                'rating': Decimal('4.8'),
                'review_count': 130,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Sugarcane',
                'tagline': 'Freshly peeled sweet organic sugarcane chew chunks',
                'description': 'Clean peeled, crisp sugarcane batons. Savor raw natural sweetness and electrolytes straight from the farm.',
                'price': Decimal('50.00'),
                'original_price': Decimal('70.00'),
                'unit': '500g vacuum pack',
                'stock_quantity': 40,
                'freshness_tag': 'Fresh Cut',
                'is_organic': True,
                'image_url': '/fruits/sugarcane.jpg',
                'rating': Decimal('4.8'),
                'review_count': 148,
                'is_featured': False,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Watermelon',
                'tagline': 'Crisp, sweet red heart striped summer watermelon',
                'description': 'Farm-direct harvest from sunny riverbeds. Deep red crunchy heart, ultra hydrating and delicious.',
                'price': Decimal('85.00'),
                'original_price': Decimal('110.00'),
                'unit': '1 pc (2.5 - 3 kg)',
                'stock_quantity': 35,
                'freshness_tag': 'Sugar Crisp',
                'is_organic': True,
                'image_url': '/fruits/watermelon.jpg',
                'rating': Decimal('4.8'),
                'review_count': 230,
                'is_featured': True,
            },
            {
                'category': categories_dict['fruits'],
                'name': 'Wood Apple (Bael)',
                'tagline': 'Traditional hard-shelled aromatic bael fruit',
                'description': 'Traditional sacred fruit with sweet, aromatic orange pulp. Famous for soothing summer drinks and digestion.',
                'price': Decimal('60.00'),
                'original_price': Decimal('80.00'),
                'unit': '1 pc',
                'stock_quantity': 25,
                'freshness_tag': 'Herbal Bael',
                'is_organic': True,
                'image_url': '/fruits/wood_apple.jpg',
                'rating': Decimal('4.6'),
                'review_count': 54,
                'is_featured': False,
            },

            # === Leafy Greens (All 12 items) ===
            {
                'category': categories_dict['greens'],
                'name': 'Spinach (Palak)',
                'tagline': 'Tender, iron-rich fresh green spinach leaves',
                'description': 'Farm-fresh emerald spinach leaves rich in iron, calcium, and vitamins. Cleanly bunched and tender.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '250g bunch',
                'stock_quantity': 80,
                'freshness_tag': 'Morning Harvest',
                'is_organic': True,
                'image_url': '/greens/spinach_palak.jpg',
                'rating': Decimal('4.9'),
                'review_count': 324,
                'is_featured': True,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Coriander (Dhaniya)',
                'tagline': 'Fragrant native fresh coriander leaves with crisp stems',
                'description': 'Aromatic, hand-harvested native cilantro essential for everyday garnishing and chutneys.',
                'price': Decimal('15.00'),
                'original_price': Decimal('25.00'),
                'unit': '100g bunch',
                'stock_quantity': 100,
                'freshness_tag': 'Daily Essential',
                'is_organic': True,
                'image_url': '/greens/coriandar.jpg',
                'rating': Decimal('4.8'),
                'review_count': 512,
                'is_featured': True,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Curry Leaves',
                'tagline': 'Aromatic, intensely flavorful fresh curry leaves',
                'description': 'Dark green glossy leaves with distinct herbal perfume. Essential for traditional tadka and tempering.',
                'price': Decimal('15.00'),
                'original_price': Decimal('20.00'),
                'unit': '100g bunch',
                'stock_quantity': 90,
                'freshness_tag': 'Intense Aroma',
                'is_organic': True,
                'image_url': '/greens/curry_leaves.jpg',
                'rating': Decimal('4.9'),
                'review_count': 380,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Mint (Pudina)',
                'tagline': 'Cooling, aromatic fresh garden mint leaves',
                'description': 'Invigorating fragrant mint sprigs perfect for cooling summer drinks, raitas, and fresh chutneys.',
                'price': Decimal('20.00'),
                'original_price': Decimal('30.00'),
                'unit': '100g bunch',
                'stock_quantity': 75,
                'freshness_tag': 'Farm Fresh',
                'is_organic': True,
                'image_url': '/greens/mint.jpg',
                'rating': Decimal('4.8'),
                'review_count': 295,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Methi (Fenugreek)',
                'tagline': 'Tender, slightly bitter-sweet fresh fenugreek greens',
                'description': 'Young, aromatic fenugreek leaves rich in dietary fiber and essential minerals. Perfect for aloo methi or parathas.',
                'price': Decimal('30.00'),
                'original_price': Decimal('45.00'),
                'unit': '250g bunch',
                'stock_quantity': 65,
                'freshness_tag': 'Tender Micro',
                'is_organic': True,
                'image_url': '/greens/menthikura.jpg',
                'rating': Decimal('4.8'),
                'review_count': 210,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Gongura Leaves',
                'tagline': 'Tangy, iron-rich traditional Andhra roselle leaves',
                'description': 'Distinctive pleasantly sour red sorrel leaves famous for authentic Gongura pachadi and curries.',
                'price': Decimal('30.00'),
                'original_price': Decimal('45.00'),
                'unit': '250g bunch',
                'stock_quantity': 50,
                'freshness_tag': 'Tangy Sorrel',
                'is_organic': True,
                'image_url': '/greens/gongura.jpg',
                'rating': Decimal('4.9'),
                'review_count': 188,
                'is_featured': True,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Amaranth (Thotakura)',
                'tagline': 'Wholesome tender green amaranth leaves rich in calcium',
                'description': 'Nutrient-rich staple green with soft leaves and tender stems. Packed with dietary fiber and vitamins.',
                'price': Decimal('25.00'),
                'original_price': Decimal('35.00'),
                'unit': '250g bunch',
                'stock_quantity': 60,
                'freshness_tag': 'Nutritious',
                'is_organic': True,
                'image_url': '/greens/thotakura.jpg',
                'rating': Decimal('4.7'),
                'review_count': 145,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Malabar Spinach',
                'tagline': 'Succulent, cooling thick-leafed climbing spinach',
                'description': 'Thick, glossy heart-shaped leaves with high mucilage and cooling properties. Ideal for dals and sambars.',
                'price': Decimal('35.00'),
                'original_price': Decimal('50.00'),
                'unit': '250g bunch',
                'stock_quantity': 40,
                'freshness_tag': 'Succulent Bachali',
                'is_organic': True,
                'image_url': '/greens/bachalakura.jpg',
                'rating': Decimal('4.8'),
                'review_count': 96,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Sorrel (Chukakura)',
                'tagline': 'Pleasantly sour, juicy green sorrel cooking leaves',
                'description': 'Tender tangy leaves providing a refreshing citrusy zest to lentils and leafy stir-fries.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '250g bunch',
                'stock_quantity': 45,
                'freshness_tag': 'Zesty Green',
                'is_organic': True,
                'image_url': '/greens/chukakura.jpg',
                'rating': Decimal('4.7'),
                'review_count': 84,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Moringa Leaves',
                'tagline': 'Nutrient-dense superfood drumstick leaves packed with vitamins',
                'description': 'Ancient Ayurvedic superfood tiny leaves brimming with protein, iron, and powerful antioxidants.',
                'price': Decimal('35.00'),
                'original_price': Decimal('50.00'),
                'unit': '200g pack',
                'stock_quantity': 55,
                'freshness_tag': 'Superfood Munaga',
                'is_organic': True,
                'image_url': '/greens/munagaku.jpg',
                'rating': Decimal('4.9'),
                'review_count': 230,
                'is_featured': True,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Ponnaganti Leaves',
                'tagline': 'Traditional cooling herbal water-amaranth greens for wellness',
                'description': 'Revered in traditional medicine for eye health and cooling properties. Mild, tender earthy flavor.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '250g bunch',
                'stock_quantity': 40,
                'freshness_tag': 'Herbal Wellness',
                'is_organic': True,
                'image_url': '/greens/ponnaganti.jpg',
                'rating': Decimal('4.8'),
                'review_count': 112,
                'is_featured': False,
            },
            {
                'category': categories_dict['greens'],
                'name': 'Spring Onions',
                'tagline': 'Crisp green scallion stalks with mild white bulbs',
                'description': 'Crunchy hollow green stems with tender pungent bulbs. Ideal for stir-fries, fried rice, and salads.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '250g bunch',
                'stock_quantity': 70,
                'freshness_tag': 'Crisp Scallions',
                'is_organic': True,
                'image_url': '/greens/springoninos.jpg',
                'rating': Decimal('4.8'),
                'review_count': 175,
                'is_featured': False,
            },

            # === Daily Veggies (All 35 items) ===
            {
                'category': categories_dict['veggies'],
                'name': 'Ash Gourd',
                'tagline': 'Hydrating, cooling native white pumpkin with mild flavor',
                'description': 'Low-calorie, highly cooling winter melon prized in Indian wellness for detox juices and soothing curries.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '1 pc (approx 1 kg)',
                'stock_quantity': 40,
                'freshness_tag': 'Hydrating Detox',
                'is_organic': True,
                'image_url': '/veggies/ashgourd.jpg',
                'rating': Decimal('4.8'),
                'review_count': 114,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Beetroot',
                'tagline': 'Deep crimson, sweet and earthy antioxidant-packed roots',
                'description': 'Crisp and juicy ruby-red beetroots rich in iron, nitrates, and folates. Excellent for juices and salads.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '500g pack',
                'stock_quantity': 55,
                'freshness_tag': 'Iron Rich',
                'is_organic': True,
                'image_url': '/veggies/beetroot.jpg',
                'rating': Decimal('4.8'),
                'review_count': 230,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Bitter Gourd (Karela)',
                'tagline': 'Crisp, ridged emerald karela revered for blood sugar wellness',
                'description': 'Firm, crunchy bitter gourds harvested young for minimal bitterness. Ideal for bharwa karela or crispy fry.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '500g pack',
                'stock_quantity': 45,
                'freshness_tag': 'Wellness Superfood',
                'is_organic': True,
                'image_url': '/veggies/bittergourd.jpg',
                'rating': Decimal('4.7'),
                'review_count': 168,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Bottle Gourd (Lauki)',
                'tagline': 'Tender, light green lauki with sweet succulent flesh',
                'description': 'Cooling, easily digestible gourd packed with water and dietary fiber. Perfect for comforting dals, sabzis, or juice.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '1 pc (approx 800g)',
                'stock_quantity': 50,
                'freshness_tag': 'Cooling Farm Fresh',
                'is_organic': True,
                'image_url': '/veggies/bottlegourd.jpg',
                'rating': Decimal('4.8'),
                'review_count': 195,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Broccoli',
                'tagline': 'Dense, emerald florets rich in vitamins and sulforaphane',
                'description': 'Tender, crunchy broccoli crowns cultivated in cool climate farms. Ideal for steaming, stir-fries, and pasta.',
                'price': Decimal('75.00'),
                'original_price': Decimal('95.00'),
                'unit': '1 pc (approx 400g)',
                'stock_quantity': 35,
                'freshness_tag': 'Super Green',
                'is_organic': True,
                'image_url': '/veggies/broccoli.jpg',
                'rating': Decimal('4.9'),
                'review_count': 260,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Cabbage',
                'tagline': 'Tightly packed, crisp green leaves with sweet crunch',
                'description': 'Farm-fresh round green cabbage. Holds crispness well in salads, stir-fries, momos, and traditional poriyals.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '1 pc (approx 600g)',
                'stock_quantity': 60,
                'freshness_tag': 'Crisp Farm Pick',
                'is_organic': True,
                'image_url': '/veggies/cabbage.jpg',
                'rating': Decimal('4.7'),
                'review_count': 175,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Carrots',
                'tagline': 'Crunchy, naturally sweet vibrant orange table carrots',
                'description': 'Clean washed, sweet juicy carrots loaded with Beta-Carotene and Vitamin A. Great for raw snacking or cooking.',
                'price': Decimal('45.00'),
                'original_price': Decimal('60.00'),
                'unit': '500g pack',
                'stock_quantity': 65,
                'freshness_tag': 'Sweet & Crisp',
                'is_organic': True,
                'image_url': '/veggies/carrot.jpg',
                'rating': Decimal('4.9'),
                'review_count': 310,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Cauliflower',
                'tagline': 'Creamy-white, spotless dense curds wrapped in fresh leaves',
                'description': 'Compact, crisp cauliflower head. Chemical-free cultivation preserving pure flavor for aloo gobi or roasting.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '1 pc (approx 600g)',
                'stock_quantity': 50,
                'freshness_tag': 'Farm Harvested',
                'is_organic': True,
                'image_url': '/veggies/cauliflower.jpg',
                'rating': Decimal('4.8'),
                'review_count': 225,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Cluster Beans (Gawar)',
                'tagline': 'Tender, fiber-rich native cluster beans with delicate nutty taste',
                'description': 'Crisp green gawar phali harvested young for zero fiber toughness. Classic Indian comfort sabzi staple.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '250g pack',
                'stock_quantity': 45,
                'freshness_tag': 'High Fiber',
                'is_organic': True,
                'image_url': '/veggies/clusterbeans.jpg',
                'rating': Decimal('4.7'),
                'review_count': 130,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Fresh Coconut',
                'tagline': 'Fresh whole brown coconut with sweet meat and rich water',
                'description': 'Freshly de-husked coconut filled with refreshing electrolyte water and thick, creamy white edible kernel.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '1 pc',
                'stock_quantity': 75,
                'freshness_tag': 'Sweet Kernel',
                'is_organic': True,
                'image_url': '/veggies/coconut.jpg',
                'rating': Decimal('4.9'),
                'review_count': 420,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Colocasia (Arbi)',
                'tagline': 'Nutty, starchy taro root bulbs with earthy richness',
                'description': 'Firm brown arbi tubers. High in gut-healthy resistant starch, delicious boiled, spiced, and roasted crispy.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '500g pack',
                'stock_quantity': 40,
                'freshness_tag': 'Starch Rich',
                'is_organic': True,
                'image_url': '/veggies/colacasia.jpg',
                'rating': Decimal('4.7'),
                'review_count': 118,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Cucumber (Kheera)',
                'tagline': 'Juicy, crisp field-grown Indian salad cucumbers',
                'description': 'Ultra-hydrating, refreshing cucumbers with thin skin and tender seeds. Cooling addition to any daily meal.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '500g pack (3-4 pcs)',
                'stock_quantity': 70,
                'freshness_tag': 'Crisp & Juicy',
                'is_organic': True,
                'image_url': '/veggies/cucumber.jpg',
                'rating': Decimal('4.8'),
                'review_count': 285,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Drumsticks (Sahjan)',
                'tagline': 'Tender, flavorful moringa pods for sambar and curries',
                'description': 'Fresh, juicy drumstick pods packed with marrow. Infuses unmistakable fragrant sweetness into dals and gravies.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '250g pack (4-5 pcs)',
                'stock_quantity': 50,
                'freshness_tag': 'Rich in Minerals',
                'is_organic': True,
                'image_url': '/veggies/drumstick.jpg',
                'rating': Decimal('4.8'),
                'review_count': 190,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Brinjal (Eggplant)',
                'tagline': 'Glossy deep purple tender eggplants with creamy flesh',
                'description': 'Tender, spotless baingan. Melts into a velvety texture when roasted for bharta or simmered in curries.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '500g pack (3-4 pcs)',
                'stock_quantity': 60,
                'freshness_tag': 'Tender Purple',
                'is_organic': True,
                'image_url': '/veggies/eggplant.jpg',
                'rating': Decimal('4.8'),
                'review_count': 215,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'French Beans',
                'tagline': 'Crisp, stringless tender green beans handpicked at dawn',
                'description': 'Slender, snap-fresh green beans rich in dietary fiber and folate. Slices effortlessly for quick everyday stir-fries.',
                'price': Decimal('40.00'),
                'original_price': Decimal('50.00'),
                'unit': '250g pack',
                'stock_quantity': 55,
                'freshness_tag': 'Snap Fresh',
                'is_organic': True,
                'image_url': '/veggies/frenchbeans.jpg',
                'rating': Decimal('4.8'),
                'review_count': 180,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Garlic (Lahsun)',
                'tagline': 'Pungent, firm Indian native garlic pods with bold aroma',
                'description': 'Tight papery skin enclosing intensely aromatic cloves. Essential for tadka, medicinal immunity, and flavoring.',
                'price': Decimal('55.00'),
                'original_price': Decimal('75.00'),
                'unit': '250g pack',
                'stock_quantity': 80,
                'freshness_tag': 'Aromatic Bulb',
                'is_organic': True,
                'image_url': '/veggies/garlic.jpg',
                'rating': Decimal('4.9'),
                'review_count': 340,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Ginger (Adrak)',
                'tagline': 'Spicy, zesty fresh mountain ginger rhizomes',
                'description': 'Juicy, fibrous ginger roots bursting with gingerol and warmth. Indispensable for morning chai, curries, and remedies.',
                'price': Decimal('45.00'),
                'original_price': Decimal('60.00'),
                'unit': '250g pack',
                'stock_quantity': 75,
                'freshness_tag': 'Spicy Warmth',
                'is_organic': True,
                'image_url': '/veggies/ginger.jpg',
                'rating': Decimal('4.9'),
                'review_count': 325,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Green Capsicum',
                'tagline': 'Crunchy, thick-walled fresh green bell peppers',
                'description': 'Plump, glossy green capsicums harvested with morning dew. Holds crunch in kadai dishes and tossed salads.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '500g pack (3 pcs)',
                'stock_quantity': 55,
                'freshness_tag': 'Crisp & Juicy',
                'is_organic': True,
                'image_url': '/veggies/greencapsicum.jpg',
                'rating': Decimal('4.8'),
                'review_count': 195,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Green Chillies',
                'tagline': 'Fiery, aromatic fresh slender green Indian chillies',
                'description': 'Vibrant green chillies picked for bold heat and pungent aroma. A must-have seasoning for Indian kitchens.',
                'price': Decimal('20.00'),
                'original_price': Decimal('28.00'),
                'unit': '100g pack',
                'stock_quantity': 90,
                'freshness_tag': 'Fiery Fresh',
                'is_organic': True,
                'image_url': '/veggies/greenchilis.jpg',
                'rating': Decimal('4.8'),
                'review_count': 280,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Ivy Gourd (Tindora)',
                'tagline': 'Crunchy, tender baby tindora with pleasant nutty taste',
                'description': 'Firm, striped miniature gourds packed with antioxidants. Crisp and delicious when sautéed with roasted spices.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '250g pack',
                'stock_quantity': 45,
                'freshness_tag': 'Tender Tindora',
                'is_organic': True,
                'image_url': '/veggies/ivygourd.jpg',
                'rating': Decimal('4.7'),
                'review_count': 140,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Lemons (Nimbu)',
                'tagline': 'Juicy, thin-skinned yellow kagzi lemons loaded with juice',
                'description': 'Fragrant and zesty sour citrus bursting with Vitamin C. Perfect for fresh shikanji, seasoning, and marinades.',
                'price': Decimal('25.00'),
                'original_price': Decimal('35.00'),
                'unit': '4 pcs pack',
                'stock_quantity': 100,
                'freshness_tag': 'Zesty Tang',
                'is_organic': True,
                'image_url': '/veggies/lemons.jpg',
                'rating': Decimal('4.9'),
                'review_count': 380,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Button Mushrooms',
                'tagline': 'Spotless, firm and hygienic fresh white button mushrooms',
                'description': 'Cultivated in sterile climate humidity. Earthy, umami-rich, packed same day for maximum freshness and texture.',
                'price': Decimal('60.00'),
                'original_price': Decimal('80.00'),
                'unit': '200g punnet',
                'stock_quantity': 45,
                'freshness_tag': 'Packed Same Day',
                'is_organic': True,
                'image_url': '/veggies/mushrooms.jpg',
                'rating': Decimal('4.8'),
                'review_count': 240,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Lady Finger (Bhindi)',
                'tagline': 'Tender, slender green okra with zero fibrous toughness',
                'description': 'Hand-sorted baby okra that snaps easily at the tip. Non-sticky when cooked into delicious kurkuri or masala bhindi.',
                'price': Decimal('35.00'),
                'original_price': Decimal('48.00'),
                'unit': '500g pack',
                'stock_quantity': 65,
                'freshness_tag': 'Tender Baby Okra',
                'is_organic': True,
                'image_url': '/veggies/okra.jpg',
                'rating': Decimal('4.8'),
                'review_count': 260,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Onions (Pyaz)',
                'tagline': 'Pungent, firm Indian cooking onions direct from mandi',
                'description': 'Essential kitchen backbone with thin papery skin and juicy, flavorful layers. Long lasting and rich in taste.',
                'price': Decimal('60.00'),
                'original_price': Decimal('80.00'),
                'unit': '2 kg bag',
                'stock_quantity': 100,
                'freshness_tag': 'Direct from Mandi',
                'is_organic': False,
                'image_url': '/veggies/onions.jpg',
                'rating': Decimal('4.8'),
                'review_count': 690,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Green Peas (Matar)',
                'tagline': 'Sweet, plump emerald peas harvested from cool hills',
                'description': 'Naturally sweet green peas bursting with tenderness. Wonderful in pulav, matar paneer, or enjoyed steamed.',
                'price': Decimal('50.00'),
                'original_price': Decimal('70.00'),
                'unit': '500g pack',
                'stock_quantity': 60,
                'freshness_tag': 'Sweet Green',
                'is_organic': True,
                'image_url': '/veggies/peas.jpg',
                'rating': Decimal('4.9'),
                'review_count': 285,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Potatoes (Aloo)',
                'tagline': 'Clean, thin-skinned everyday cooking potatoes',
                'description': 'Smooth, unblemished all-purpose potatoes with firm texture. Ideal for roasting, boiling, parathas, and curries.',
                'price': Decimal('50.00'),
                'original_price': Decimal('70.00'),
                'unit': '2 kg bag',
                'stock_quantity': 110,
                'freshness_tag': 'Farm Dug Fresh',
                'is_organic': True,
                'image_url': '/veggies/potatoes.jpg',
                'rating': Decimal('4.8'),
                'review_count': 560,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Pumpkin (Kaddu)',
                'tagline': 'Golden-orange sweet pumpkin with rich creamy flesh',
                'description': 'Naturally sweet winter squash rich in Vitamin A, zinc, and fiber. Superb for comforting soups, sambar, and sabzi.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '1 pc (approx 1 kg)',
                'stock_quantity': 40,
                'freshness_tag': 'Golden Sweet',
                'is_organic': True,
                'image_url': '/veggies/pumpkin.jpg',
                'rating': Decimal('4.7'),
                'review_count': 150,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'White Radish (Mooli)',
                'tagline': 'Crisp, peppery white radish with vibrant green leaves',
                'description': 'Clean white crunchy root with pleasant peppery bite. Great for digestion, mooli parathas, and fresh winter salads.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '500g pack (2-3 pcs)',
                'stock_quantity': 50,
                'freshness_tag': 'Crunchy Peppery',
                'is_organic': True,
                'image_url': '/veggies/radish.jpg',
                'rating': Decimal('4.7'),
                'review_count': 160,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Raw Banana (Plantain)',
                'tagline': 'Firm green cooking bananas rich in prebiotic starch',
                'description': 'Dense, firm plantains traditional in South Indian cooking for chips, thoran, curries, and crispy roasts.',
                'price': Decimal('30.00'),
                'original_price': Decimal('40.00'),
                'unit': '3 pcs pack',
                'stock_quantity': 55,
                'freshness_tag': 'Cooking Plantain',
                'is_organic': True,
                'image_url': '/veggies/rawbanana.jpg',
                'rating': Decimal('4.8'),
                'review_count': 175,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Raw Mango (Kaccha Aam)',
                'tagline': 'Tangy, firm sour raw green mangoes for chutneys',
                'description': 'Puckery sour green mango with crunchy white flesh. Essential for aam panna, spicy pickles, and summer dals.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '500g pack (2 pcs)',
                'stock_quantity': 45,
                'freshness_tag': 'Tangy Sour',
                'is_organic': True,
                'image_url': '/veggies/rawmango.jpg',
                'rating': Decimal('4.9'),
                'review_count': 210,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Red Capsicum',
                'tagline': 'Sweet, vibrant ruby-red bell peppers packed with Vitamin C',
                'description': 'Sun-ripened red capsicums with thick juicy walls and gentle natural sweetness. Elevates pasta, grills, and salads.',
                'price': Decimal('65.00'),
                'original_price': Decimal('85.00'),
                'unit': '2 pcs (approx 350g)',
                'stock_quantity': 40,
                'freshness_tag': 'Sweet Ruby',
                'is_organic': True,
                'image_url': '/veggies/redcapcicum.jpg',
                'rating': Decimal('4.8'),
                'review_count': 185,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Ridge Gourd (Turai)',
                'tagline': 'Tender, cooling ridged gourd with sweet soft flesh',
                'description': 'Mild and delicate vegetable high in dietary water and low in calories. Highly comforting in everyday home cooking.',
                'price': Decimal('35.00'),
                'original_price': Decimal('45.00'),
                'unit': '500g pack (2-3 pcs)',
                'stock_quantity': 50,
                'freshness_tag': 'Cooling Turai',
                'is_organic': True,
                'image_url': '/veggies/ridgegourd.jpg',
                'rating': Decimal('4.7'),
                'review_count': 135,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Sweet Corn',
                'tagline': 'Golden, milky sweet corn cobs with tender kernels',
                'description': 'Plump yellow corn cobs bursting with juicy natural sweetness. Delicious boiled with butter and chaat masala.',
                'price': Decimal('35.00'),
                'original_price': Decimal('50.00'),
                'unit': '2 pcs pack',
                'stock_quantity': 65,
                'freshness_tag': 'Milky Sweet',
                'is_organic': True,
                'image_url': '/veggies/sweetcorn.jpg',
                'rating': Decimal('4.9'),
                'review_count': 290,
                'is_featured': True,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Sweet Potatoes (Shakarkandi)',
                'tagline': 'Caramel-rich purple-skin sweet potatoes packed with energy',
                'description': 'Naturally sweet starchy tubers high in fiber and beta-carotene. Irresistible roasted with lemon juice and chaat masala.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '500g pack',
                'stock_quantity': 50,
                'freshness_tag': 'Slow Energy',
                'is_organic': True,
                'image_url': '/veggies/sweetpotatoes.jpg',
                'rating': Decimal('4.8'),
                'review_count': 195,
                'is_featured': False,
            },
            {
                'category': categories_dict['veggies'],
                'name': 'Tomatoes (Tamatar)',
                'tagline': 'Firm, juicy red ripe country tomatoes with balanced tang',
                'description': 'Vine-ripened local desi tomatoes boasting sweet-tart acidity and thick pulp. The indispensable heart of Indian cooking.',
                'price': Decimal('40.00'),
                'original_price': Decimal('55.00'),
                'unit': '1 kg pack',
                'stock_quantity': 100,
                'freshness_tag': 'Vine Ripened',
                'is_organic': True,
                'image_url': '/veggies/tomatoes.jpg',
                'rating': Decimal('4.9'),
                'review_count': 640,
                'is_featured': True,
            },
        ]

        created_count = 0
        for p_data in products_data:
            Product.objects.create(**p_data)
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded database: {len(categories_data)} categories, "
                f"{created_count} products created with all 46 fruit items."
            )
        )
