import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Observable, catchError, map, of } from 'rxjs';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';
import { OrderRequest, OrderResponse } from '../models/order.model';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  private http = inject(HttpClient);
  private readonly baseUrl = 'http://localhost:8000/api';

  /**
   * Fallback dataset with authentic Indian organic farm produce
   * in case Django backend is disconnected during offline preview.
   */
  private readonly fallbackCategories: Category[] = [
    { id: 1, name: 'Fresh Fruits', slug: 'fruits', icon: '🍎', display_order: 1, products_count: 46 },
    { id: 2, name: 'Leafy Greens', slug: 'greens', icon: '🥬', display_order: 2, products_count: 12 },
    { id: 3, name: 'Daily Veggies', slug: 'veggies', icon: '🥕', display_order: 3, products_count: 35 },
  ];

  private readonly fallbackProducts: Product[] = [
    // === All 46 Fruits with simple naming ===
    {
      id: 1,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Apples',
      tagline: 'Crisp, naturally sweet orchard-picked red apples',
      description: 'Crunchy and juicy fresh apples grown in sunny mountain slopes, free from artificial wax.',
      price: 180.00,
      original_price: 220.00,
      discount_percentage: 18,
      unit: '1 kg (4-5 pcs)',
      stock_quantity: 50,
      freshness_tag: 'Orchard Fresh',
      is_organic: true,
      image_url: '/fruits/apples.jpg',
      rating: 4.9,
      review_count: 248,
      is_featured: true,
    },
    {
      id: 2,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Apricots',
      tagline: 'Golden-orange sweet and tangy fresh apricots',
      description: 'Plump sun-ripened apricots packed with vitamins, dietary fiber, and delicate floral sweetness.',
      price: 260.00,
      original_price: 320.00,
      discount_percentage: 19,
      unit: '500g box',
      stock_quantity: 35,
      freshness_tag: 'Farm Fresh',
      is_organic: true,
      image_url: '/fruits/apricots.jpg',
      rating: 4.8,
      review_count: 112,
      is_featured: false,
    },
    {
      id: 3,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Avocados',
      tagline: 'Creamy, nutty Hass avocados perfect for guacamole & toast',
      description: 'Rich in heart-healthy natural oils. Buttery smooth texture that mashes effortlessly.',
      price: 180.00,
      original_price: 220.00,
      discount_percentage: 18,
      unit: '2 pcs (approx 450g)',
      stock_quantity: 40,
      freshness_tag: 'Creamy Ripe',
      is_organic: true,
      image_url: '/fruits/avacados.jpg',
      rating: 4.9,
      review_count: 324,
      is_featured: true,
    },
    {
      id: 4,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Bananas',
      tagline: 'Naturally tree-ripened sweet yellow bananas',
      description: 'Wholesome everyday bananas rich in potassium and energy. Ripened without harmful chemicals.',
      price: 60.00,
      original_price: 80.00,
      discount_percentage: 25,
      unit: '1 kg (10-12 pcs)',
      stock_quantity: 80,
      freshness_tag: 'Tree Ripened',
      is_organic: true,
      image_url: '/fruits/bananas.jpg',
      rating: 4.8,
      review_count: 318,
      is_featured: false,
    },
    {
      id: 5,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Blackberries',
      tagline: 'Juicy, antioxidant-packed sweet wild blackberries',
      description: 'Deep purple, plump wild berries freshly picked from highland brambles. Wonderful in yogurt or raw.',
      price: 180.00,
      original_price: 230.00,
      discount_percentage: 22,
      unit: '150g punnet',
      stock_quantity: 25,
      freshness_tag: 'Superfood',
      is_organic: true,
      image_url: '/fruits/black_berry.jpg',
      rating: 4.9,
      review_count: 94,
      is_featured: false,
    },
    {
      id: 6,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Blackcurrants',
      tagline: 'Tart-sweet aromatic blackcurrants bursting with flavor',
      description: 'Glossy dark berries celebrated for rich antioxidants, baking, and refreshing juices.',
      price: 200.00,
      original_price: 250.00,
      discount_percentage: 20,
      unit: '200g box',
      stock_quantity: 20,
      freshness_tag: 'High Vitamin C',
      is_organic: true,
      image_url: '/fruits/black_current.jpg',
      rating: 4.7,
      review_count: 76,
      is_featured: false,
    },
    {
      id: 7,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Black Grapes',
      tagline: 'Crisp, sweet seedless midnight-black grapes',
      description: 'Naturally sun-sweetened with thin skins and rich anthocyanins. Pre-washed in clean ozonated water.',
      price: 90.00,
      original_price: 120.00,
      discount_percentage: 25,
      unit: '500g punnet',
      stock_quantity: 45,
      freshness_tag: 'Seedless',
      is_organic: true,
      image_url: '/fruits/black_grapes.jpg',
      rating: 4.9,
      review_count: 210,
      is_featured: true,
    },
    {
      id: 8,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Blueberries',
      tagline: 'Plump indigo sweet blueberries with silver bloom',
      description: 'Pesticide-free cultivated berries. Sweet, juicy, and delicious for morning smoothies and breakfast.',
      price: 220.00,
      original_price: 280.00,
      discount_percentage: 21,
      unit: '125g punnet',
      stock_quantity: 30,
      freshness_tag: 'Antioxidant Rich',
      is_organic: true,
      image_url: '/fruits/blue_berries.jpg',
      rating: 4.9,
      review_count: 142,
      is_featured: false,
    },
    {
      id: 9,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Cashew Apples',
      tagline: 'Fragrant, juicy tropical cashew fruit with exotic aroma',
      description: 'Unique, vibrant tropical fruit packed with five times more Vitamin C than oranges. Intensely juicy.',
      price: 120.00,
      original_price: 160.00,
      discount_percentage: 25,
      unit: '500g pack',
      stock_quantity: 25,
      freshness_tag: 'Tropical Rare',
      is_organic: true,
      image_url: '/fruits/cashewapples.jpg',
      rating: 4.6,
      review_count: 58,
      is_featured: false,
    },
    {
      id: 10,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Cherries',
      tagline: 'Sweet, ruby-red juicy mountain cherries',
      description: 'Crisp, glossy cherries handpicked from high elevation orchards. Perfect fresh sweet crunch.',
      price: 320.00,
      original_price: 400.00,
      discount_percentage: 20,
      unit: '500g box',
      stock_quantity: 25,
      freshness_tag: 'Valley Fresh',
      is_organic: true,
      image_url: '/fruits/cherries.jpg',
      rating: 5.0,
      review_count: 156,
      is_featured: true,
    },
    {
      id: 11,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Cranberries',
      tagline: 'Bright red, tart and zesty nutrient-dense cranberries',
      description: 'Vibrant red berries known for wellness and refreshing tartness. Excellent for juices and sauces.',
      price: 210.00,
      original_price: 260.00,
      discount_percentage: 19,
      unit: '200g box',
      stock_quantity: 20,
      freshness_tag: 'Wellness Superfood',
      is_organic: true,
      image_url: '/fruits/cranberries.jpg',
      rating: 4.7,
      review_count: 82,
      is_featured: false,
    },
    {
      id: 12,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Custard Apples',
      tagline: 'Creamy, sweet sugar-apple pulp with heavenly aroma',
      description: 'Naturally soft Sitaphal with rich sugary segments. Packed with magnesium, calcium, and vitamin B6.',
      price: 130.00,
      original_price: 170.00,
      discount_percentage: 23,
      unit: '1 kg (3-4 pcs)',
      stock_quantity: 35,
      freshness_tag: 'Honey Sweet',
      is_organic: true,
      image_url: '/fruits/custard_apples.jpg',
      rating: 4.9,
      review_count: 172,
      is_featured: true,
    },
    {
      id: 13,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Dragon Fruit',
      tagline: 'Vibrant fuchsia pitaya with delicate sweetness',
      description: 'Exotic dragon fruit with jewel-pink exterior and crunchy seed-speckled pulp. Packed with prebiotics.',
      price: 110.00,
      original_price: 150.00,
      discount_percentage: 27,
      unit: '1 pc (approx 350g)',
      stock_quantity: 40,
      freshness_tag: 'Exotic Pick',
      is_organic: true,
      image_url: '/fruits/dragonfruits.jpg',
      rating: 4.8,
      review_count: 195,
      is_featured: false,
    },
    {
      id: 14,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Durian',
      tagline: 'The King of Fruits with rich, golden creamy custard pods',
      description: 'Distinctive exotic specialty fruit with golden-yellow custard pods possessing rich creamy sweetness.',
      price: 750.00,
      original_price: 950.00,
      discount_percentage: 21,
      unit: '1 kg',
      stock_quantity: 15,
      freshness_tag: 'Exotic King',
      is_organic: true,
      image_url: '/fruits/durian.jpg',
      rating: 4.7,
      review_count: 88,
      is_featured: false,
    },
    {
      id: 15,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Figs',
      tagline: 'Plump fresh purple figs dripping with delicate honey sweetness',
      description: 'Tender sweet Anjeer freshly plucked from orchards. Superb source of natural calcium and dietary fiber.',
      price: 130.00,
      original_price: 170.00,
      discount_percentage: 23,
      unit: '500g box',
      stock_quantity: 25,
      freshness_tag: 'Tender & Sweet',
      is_organic: true,
      image_url: '/fruits/figs.jpg',
      rating: 4.9,
      review_count: 115,
      is_featured: false,
    },
    {
      id: 16,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Gooseberries (Amla)',
      tagline: 'Wild, immunity-boosting Indian amla rich in Vitamin C',
      description: 'Crisp, tangy-tart green amla berries traditionally celebrated in Ayurveda for gut health and immunity.',
      price: 60.00,
      original_price: 85.00,
      discount_percentage: 29,
      unit: '500g pack',
      stock_quantity: 60,
      freshness_tag: 'Ayurvedic Amla',
      is_organic: true,
      image_url: '/fruits/gooseberries.jpg',
      rating: 4.8,
      review_count: 164,
      is_featured: false,
    },
    {
      id: 17,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Grapefruit',
      tagline: 'Juicy ruby-red citrus with crisp bittersweet refreshing flavor',
      description: 'Thick-peeled, vibrant pink citrus segments loaded with lycopene, vitamin C, and revitalizing juice.',
      price: 120.00,
      original_price: 150.00,
      discount_percentage: 20,
      unit: '2 pcs (approx 600g)',
      stock_quantity: 35,
      freshness_tag: 'Ruby Red',
      is_organic: true,
      image_url: '/fruits/grape_fruit.jpg',
      rating: 4.7,
      review_count: 78,
      is_featured: false,
    },
    {
      id: 18,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Green Apples',
      tagline: 'Ultra-crisp, tangy Granny Smith green apples',
      description: 'Bright emerald skin with tart, crunchy flesh. Excellent for juicing, fresh salads, or crisp snacking.',
      price: 210.00,
      original_price: 250.00,
      discount_percentage: 16,
      unit: '1 kg (4-5 pcs)',
      stock_quantity: 40,
      freshness_tag: 'Crisp Tart',
      is_organic: true,
      image_url: '/fruits/green_apples.jpg',
      rating: 4.8,
      review_count: 134,
      is_featured: false,
    },
    {
      id: 19,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Guava',
      tagline: 'Fragrant, white-fleshed sweet guava with edible skin',
      description: 'Mild sweet flavor with crunchy edible seeds and pleasant scent. Rich in natural pectin and fiber.',
      price: 80.00,
      original_price: 105.00,
      discount_percentage: 24,
      unit: '1 kg (4-5 pcs)',
      stock_quantity: 55,
      freshness_tag: 'Vitamin C Rich',
      is_organic: true,
      image_url: '/fruits/guava.jpg',
      rating: 4.7,
      review_count: 145,
      is_featured: false,
    },
    {
      id: 20,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Jackfruit',
      tagline: 'Tender raw or sweet ripe tropical jackfruit pods',
      description: 'Large tropical treasure with aromatic sweet golden segments or nutritious vegetable cooking bulbs.',
      price: 90.00,
      original_price: 120.00,
      discount_percentage: 25,
      unit: '500g cut pack',
      stock_quantity: 30,
      freshness_tag: 'Farm Harvested',
      is_organic: true,
      image_url: '/fruits/jackfruit.jpg',
      rating: 4.7,
      review_count: 92,
      is_featured: false,
    },
    {
      id: 21,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Jujube (Ber)',
      tagline: 'Crisp, sweet and tart native Indian plum berries',
      description: 'Small crunchy green and red berries with pleasant sweet-sour crispness reminiscent of miniature apples.',
      price: 70.00,
      original_price: 95.00,
      discount_percentage: 26,
      unit: '500g pack',
      stock_quantity: 45,
      freshness_tag: 'Seasonal Ber',
      is_organic: true,
      image_url: '/fruits/jujube.jpg',
      rating: 4.8,
      review_count: 118,
      is_featured: false,
    },
    {
      id: 22,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Kiwi',
      tagline: 'Tangy-sweet bright green kiwis loaded with Vitamin C',
      description: 'Fuzzy brown skin with radiant emerald flesh and crunchy black seeds. Boosts digestion and energy.',
      price: 120.00,
      original_price: 160.00,
      discount_percentage: 25,
      unit: '3 pcs pack',
      stock_quantity: 50,
      freshness_tag: 'Zesty Fresh',
      is_organic: true,
      image_url: '/fruits/kiwi.jpg',
      rating: 4.8,
      review_count: 168,
      is_featured: false,
    },
    {
      id: 23,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Litchi',
      tagline: 'Floral, translucent sweet pulp bursting with nectar',
      description: 'Delicate bumpy red rind peeling to reveal fragrant, succulent white pulp with intoxicating sweetness.',
      price: 220.00,
      original_price: 280.00,
      discount_percentage: 21,
      unit: '1 kg',
      stock_quantity: 30,
      freshness_tag: 'Floral Sweet',
      is_organic: true,
      image_url: '/fruits/litchi.jpg',
      rating: 4.9,
      review_count: 240,
      is_featured: false,
    },
    {
      id: 24,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Makoy Berries',
      tagline: 'Dark, sweet traditional Indian wild nightshade berries',
      description: 'Tiny black-purple berries known in herbal traditions for soothing digestion and rich nutrients.',
      price: 90.00,
      original_price: 120.00,
      discount_percentage: 25,
      unit: '250g pack',
      stock_quantity: 20,
      freshness_tag: 'Wild Herbal',
      is_organic: true,
      image_url: '/fruits/makoy.jpg',
      rating: 4.6,
      review_count: 45,
      is_featured: false,
    },
    {
      id: 25,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Rose Apples',
      tagline: 'Crisp, bell-shaped crunchy rose-scented water apples',
      description: 'Unusually crisp, thirst-quenching bell fruit with subtle rosewater fragrance and pleasant sweetness.',
      price: 150.00,
      original_price: 190.00,
      discount_percentage: 21,
      unit: '500g box',
      stock_quantity: 25,
      freshness_tag: 'Crisp Water Fruit',
      is_organic: true,
      image_url: '/fruits/malay_apple.jpg',
      rating: 4.7,
      review_count: 62,
      is_featured: false,
    },
    {
      id: 26,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Mangoes',
      tagline: 'Naturally ripened, heavenly sweet king of fruits',
      description: 'Velvety saffron pulp with an intoxicating floral fragrance. 100% carbide-free and tree-ripened.',
      price: 699.00,
      original_price: 899.00,
      discount_percentage: 22,
      unit: '6 pcs box',
      stock_quantity: 35,
      freshness_tag: 'King of Fruits',
      is_organic: true,
      image_url: '/fruits/mangoes.jpg',
      rating: 5.0,
      review_count: 482,
      is_featured: true,
    },
    {
      id: 27,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Mangosteen',
      tagline: 'The Queen of Fruits with delicate sweet white segments',
      description: 'Thick purple rind encasing soft, snow-white juicy citrus-peach flavored segments of royalty.',
      price: 320.00,
      original_price: 400.00,
      discount_percentage: 20,
      unit: '4 pcs (approx 350g)',
      stock_quantity: 20,
      freshness_tag: 'Queen of Fruits',
      is_organic: true,
      image_url: '/fruits/mangosteen.jpg',
      rating: 4.9,
      review_count: 108,
      is_featured: false,
    },
    {
      id: 28,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Mulberries',
      tagline: 'Sweet, tender crimson-black Shahtoot mulberries',
      description: 'Delicate elongated berries bursting with gentle sweet juice. Harvested with utmost care.',
      price: 110.00,
      original_price: 145.00,
      discount_percentage: 24,
      unit: '200g punnet',
      stock_quantity: 25,
      freshness_tag: 'Delicate Shahtoot',
      is_organic: true,
      image_url: '/fruits/mulberries.jpg',
      rating: 4.8,
      review_count: 96,
      is_featured: false,
    },
    {
      id: 29,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Muskmelon',
      tagline: 'Sweet, aromatic netted melon with soft honeyed orange flesh',
      description: 'Naturally fragrant cantaloupe melon. Ultra hydrating, cooling, and filled with sweet summer juice.',
      price: 75.00,
      original_price: 95.00,
      discount_percentage: 21,
      unit: '1 pc (1 - 1.2 kg)',
      stock_quantity: 40,
      freshness_tag: 'Honey Sweet',
      is_organic: true,
      image_url: '/fruits/muskmelon.jpg',
      rating: 4.8,
      review_count: 178,
      is_featured: false,
    },
    {
      id: 30,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Oranges',
      tagline: 'Juicy, sweet sun-kissed citrus bursting with Vitamin C',
      description: 'Thin peeled, tender segments full of bright sweet-tart juice. Ideal for refreshing morning juicing.',
      price: 110.00,
      original_price: 140.00,
      discount_percentage: 21,
      unit: '1 kg (5-6 pcs)',
      stock_quantity: 60,
      freshness_tag: 'Farm Picked',
      is_organic: true,
      image_url: '/fruits/oranges.jpg',
      rating: 4.8,
      review_count: 184,
      is_featured: false,
    },
    {
      id: 31,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Papaya',
      tagline: 'Sweet, buttery salmon-orange ripe dessert papaya',
      description: 'Easy-to-digest tropical fruit rich in papain enzymes and Vitamin A. Smooth sweet flavor.',
      price: 65.00,
      original_price: 85.00,
      discount_percentage: 24,
      unit: '1 pc (1 - 1.2 kg)',
      stock_quantity: 50,
      freshness_tag: 'Enzyme Rich',
      is_organic: true,
      image_url: '/fruits/papaya.jpg',
      rating: 4.8,
      review_count: 210,
      is_featured: false,
    },
    {
      id: 32,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Passion Fruit',
      tagline: 'Aromatic, tangy tropical pulp with crunchy edible seeds',
      description: 'Wrinkled purple globe containing intensely aromatic golden nectar. Elevates desserts, juices, and bowls.',
      price: 160.00,
      original_price: 200.00,
      discount_percentage: 20,
      unit: '4 pcs pack',
      stock_quantity: 25,
      freshness_tag: 'Tropical Aroma',
      is_organic: true,
      image_url: '/fruits/passionfruit.jpg',
      rating: 4.9,
      review_count: 88,
      is_featured: false,
    },
    {
      id: 33,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Peaches',
      tagline: 'Velvety, fragrant sweet yellow mountain peaches',
      description: 'Soft fuzzy skin with succulent golden flesh dripping with sweet juice. Plucked at peak ripeness.',
      price: 190.00,
      original_price: 240.00,
      discount_percentage: 21,
      unit: '500g box',
      stock_quantity: 30,
      freshness_tag: 'Hill Sourced',
      is_organic: true,
      image_url: '/fruits/peaches.jpg',
      rating: 4.8,
      review_count: 120,
      is_featured: false,
    },
    {
      id: 34,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Pears',
      tagline: 'Crisp, refreshing sweet green Nashpati pears',
      description: 'Firm green skin with crisp, grainy, juicy white flesh that refreshes the palate.',
      price: 140.00,
      original_price: 180.00,
      discount_percentage: 22,
      unit: '1 kg (4-5 pcs)',
      stock_quantity: 45,
      freshness_tag: 'Crisp Pear',
      is_organic: true,
      image_url: '/fruits/pears.jpg',
      rating: 4.7,
      review_count: 114,
      is_featured: false,
    },
    {
      id: 35,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Persimmons',
      tagline: 'Glossy orange, honey-sweet Japani phal persimmons',
      description: 'Smooth jelly-like honeyed sweetness when fully ripe. A rare winter mountain orchard specialty.',
      price: 180.00,
      original_price: 230.00,
      discount_percentage: 22,
      unit: '500g box',
      stock_quantity: 25,
      freshness_tag: 'Orchard Rare',
      is_organic: true,
      image_url: '/fruits/persimmon.jpg',
      rating: 4.8,
      review_count: 72,
      is_featured: false,
    },
    {
      id: 36,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Pineapple',
      tagline: 'Golden, sweet and fragrant Queen pineapple',
      description: 'Tropical sweet crown fruit with juicy golden flesh and tender core. Naturally rich in bromelain.',
      price: 95.00,
      original_price: 130.00,
      discount_percentage: 27,
      unit: '1 pc (approx 800g)',
      stock_quantity: 35,
      freshness_tag: 'Sweet Queen',
      is_organic: true,
      image_url: '/fruits/pineapple.jpg',
      rating: 4.9,
      review_count: 188,
      is_featured: false,
    },
    {
      id: 37,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Plums',
      tagline: 'Succulent deep red sweet and tart fresh plums',
      description: 'Smooth glossy red skin with ruby-colored juicy pulp. High in antioxidants and vitamins.',
      price: 160.00,
      original_price: 200.00,
      discount_percentage: 20,
      unit: '500g box',
      stock_quantity: 35,
      freshness_tag: 'Juicy Plums',
      is_organic: true,
      image_url: '/fruits/plums.jpg',
      rating: 4.8,
      review_count: 130,
      is_featured: false,
    },
    {
      id: 38,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Pomelo',
      tagline: 'Giant sweet citrus with mild, refreshing pink vesicles',
      description: 'The largest citrus fruit. Sweet, mild flavor without bitter aftertaste. Very easy to peel and savor.',
      price: 130.00,
      original_price: 170.00,
      discount_percentage: 24,
      unit: '1 pc (approx 1 kg)',
      stock_quantity: 25,
      freshness_tag: 'Giant Citrus',
      is_organic: true,
      image_url: '/fruits/pomelo.jpg',
      rating: 4.7,
      review_count: 64,
      is_featured: false,
    },
    {
      id: 39,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Pomegranates',
      tagline: 'Ruby-red juicy Bhagwa arils brimming with antioxidants',
      description: 'Glossy crimson pearls dripping with sweet nectar. Hand-selected for maximum sweetness and soft seeds.',
      price: 180.00,
      original_price: 230.00,
      discount_percentage: 22,
      unit: '1 kg (3-4 pcs)',
      stock_quantity: 50,
      freshness_tag: 'Bhagwa Ruby',
      is_organic: true,
      image_url: '/fruits/pomogranate.jpg',
      rating: 4.9,
      review_count: 260,
      is_featured: true,
    },
    {
      id: 40,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Raspberries',
      tagline: 'Delicate, ruby-red tart-sweet fresh raspberries',
      description: 'Melt-in-mouth berries packed with fiber, vitamin C, and radiant taste. Sourced in cold containers.',
      price: 260.00,
      original_price: 320.00,
      discount_percentage: 19,
      unit: '150g punnet',
      stock_quantity: 20,
      freshness_tag: 'Cold-Chain',
      is_organic: true,
      image_url: '/fruits/raspberries.jpg',
      rating: 4.9,
      review_count: 110,
      is_featured: false,
    },
    {
      id: 41,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Sapota (Chiku)',
      tagline: 'Caramel-sweet brown sapota with soft grainy texture',
      description: 'Rich, honeyed sweetness reminiscent of brown sugar and pears. Naturally high in calcium and energy.',
      price: 70.00,
      original_price: 95.00,
      discount_percentage: 26,
      unit: '1 kg (8-10 pcs)',
      stock_quantity: 60,
      freshness_tag: 'Caramel Sweet',
      is_organic: true,
      image_url: '/fruits/sapota.jpg',
      rating: 4.8,
      review_count: 189,
      is_featured: false,
    },
    {
      id: 42,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Star Fruit',
      tagline: 'Crisp, star-shaped yellow carambola with citrus sweetness',
      description: 'Beautiful star slices that are juicy, tangy, and thirst-quenching. Ideal for fruit platters and snacks.',
      price: 60.00,
      original_price: 85.00,
      discount_percentage: 29,
      unit: '250g pack (3-4 pcs)',
      stock_quantity: 30,
      freshness_tag: 'Crisp Carambola',
      is_organic: true,
      image_url: '/fruits/star_fruit.jpg',
      rating: 4.7,
      review_count: 82,
      is_featured: false,
    },
    {
      id: 43,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Strawberries',
      tagline: 'Plump, fragrant ruby strawberries picked at dawn',
      description: 'Misty red soil strawberries packed in protective punnets. Unbruised, aromatic, and sweet.',
      price: 160.00,
      original_price: 210.00,
      discount_percentage: 24,
      unit: '250g box',
      stock_quantity: 35,
      freshness_tag: 'Cold-Chain Express',
      is_organic: true,
      image_url: '/fruits/strawberries.jpg',
      rating: 4.8,
      review_count: 130,
      is_featured: true,
    },
    {
      id: 44,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Sugarcane',
      tagline: 'Freshly peeled sweet organic sugarcane chew chunks',
      description: 'Clean peeled, crisp sugarcane batons. Savor raw natural sweetness and electrolytes straight from the farm.',
      price: 50.00,
      original_price: 70.00,
      discount_percentage: 29,
      unit: '500g vacuum pack',
      stock_quantity: 40,
      freshness_tag: 'Fresh Cut',
      is_organic: true,
      image_url: '/fruits/sugarcane.jpg',
      rating: 4.8,
      review_count: 148,
      is_featured: false,
    },
    {
      id: 45,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Watermelon',
      tagline: 'Crisp, sweet red heart striped summer watermelon',
      description: 'Farm-direct harvest from sunny riverbeds. Deep red crunchy heart, ultra hydrating and delicious.',
      price: 85.00,
      original_price: 110.00,
      discount_percentage: 23,
      unit: '1 pc (2.5 - 3 kg)',
      stock_quantity: 35,
      freshness_tag: 'Sugar Crisp',
      is_organic: true,
      image_url: '/fruits/watermelon.jpg',
      rating: 4.8,
      review_count: 230,
      is_featured: true,
    },
    {
      id: 46,
      category: 1,
      category_name: 'Fresh Fruits',
      category_slug: 'fruits',
      name: 'Wood Apple (Bael)',
      tagline: 'Traditional hard-shelled aromatic bael fruit',
      description: 'Traditional sacred fruit with sweet, aromatic orange pulp. Famous for soothing summer drinks and digestion.',
      price: 60.00,
      original_price: 80.00,
      discount_percentage: 25,
      unit: '1 pc',
      stock_quantity: 25,
      freshness_tag: 'Herbal Bael',
      is_organic: true,
      image_url: '/fruits/wood_apple.jpg',
      rating: 4.6,
      review_count: 54,
      is_featured: false,
    },

    // === Leafy Greens (All 12 items) ===
    {
      id: 47,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Spinach (Palak)',
      tagline: 'Tender, iron-rich fresh green spinach leaves',
      description: 'Farm-fresh emerald spinach leaves rich in iron, calcium, and vitamins. Cleanly bunched and tender.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '250g bunch',
      stock_quantity: 80,
      freshness_tag: 'Morning Harvest',
      is_organic: true,
      image_url: '/greens/spinach_palak.jpg',
      rating: 4.9,
      review_count: 324,
      is_featured: true,
    },
    {
      id: 48,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Coriander (Dhaniya)',
      tagline: 'Fragrant native fresh coriander leaves with crisp stems',
      description: 'Aromatic, hand-harvested native cilantro essential for everyday garnishing and chutneys.',
      price: 15.00,
      original_price: 25.00,
      discount_percentage: 40,
      unit: '100g bunch',
      stock_quantity: 100,
      freshness_tag: 'Daily Essential',
      is_organic: true,
      image_url: '/greens/coriandar.jpg',
      rating: 4.8,
      review_count: 512,
      is_featured: true,
    },
    {
      id: 49,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Curry Leaves',
      tagline: 'Aromatic, intensely flavorful fresh curry leaves',
      description: 'Dark green glossy leaves with distinct herbal perfume. Essential for traditional tadka and tempering.',
      price: 15.00,
      original_price: 20.00,
      discount_percentage: 25,
      unit: '100g bunch',
      stock_quantity: 90,
      freshness_tag: 'Intense Aroma',
      is_organic: true,
      image_url: '/greens/curry_leaves.jpg',
      rating: 4.9,
      review_count: 380,
      is_featured: false,
    },
    {
      id: 50,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Mint (Pudina)',
      tagline: 'Cooling, aromatic fresh garden mint leaves',
      description: 'Invigorating fragrant mint sprigs perfect for cooling summer drinks, raitas, and fresh chutneys.',
      price: 20.00,
      original_price: 30.00,
      discount_percentage: 33,
      unit: '100g bunch',
      stock_quantity: 75,
      freshness_tag: 'Farm Fresh',
      is_organic: true,
      image_url: '/greens/mint.jpg',
      rating: 4.8,
      review_count: 295,
      is_featured: false,
    },
    {
      id: 51,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Methi (Fenugreek)',
      tagline: 'Tender, slightly bitter-sweet fresh fenugreek greens',
      description: 'Young, aromatic fenugreek leaves rich in dietary fiber and essential minerals. Perfect for aloo methi or parathas.',
      price: 30.00,
      original_price: 45.00,
      discount_percentage: 33,
      unit: '250g bunch',
      stock_quantity: 65,
      freshness_tag: 'Tender Micro',
      is_organic: true,
      image_url: '/greens/menthikura.jpg',
      rating: 4.8,
      review_count: 210,
      is_featured: false,
    },
    {
      id: 52,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Gongura Leaves',
      tagline: 'Tangy, iron-rich traditional Andhra roselle leaves',
      description: 'Distinctive pleasantly sour red sorrel leaves famous for authentic Gongura pachadi and curries.',
      price: 30.00,
      original_price: 45.00,
      discount_percentage: 33,
      unit: '250g bunch',
      stock_quantity: 50,
      freshness_tag: 'Tangy Sorrel',
      is_organic: true,
      image_url: '/greens/gongura.jpg',
      rating: 4.9,
      review_count: 188,
      is_featured: true,
    },
    {
      id: 53,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Amaranth (Thotakura)',
      tagline: 'Wholesome tender green amaranth leaves rich in calcium',
      description: 'Nutrient-rich staple green with soft leaves and tender stems. Packed with dietary fiber and vitamins.',
      price: 25.00,
      original_price: 35.00,
      discount_percentage: 28,
      unit: '250g bunch',
      stock_quantity: 60,
      freshness_tag: 'Nutritious',
      is_organic: true,
      image_url: '/greens/thotakura.jpg',
      rating: 4.7,
      review_count: 145,
      is_featured: false,
    },
    {
      id: 54,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Malabar Spinach',
      tagline: 'Succulent, cooling thick-leafed climbing spinach',
      description: 'Thick, glossy heart-shaped leaves with high mucilage and cooling properties. Ideal for dals and sambars.',
      price: 35.00,
      original_price: 50.00,
      discount_percentage: 30,
      unit: '250g bunch',
      stock_quantity: 40,
      freshness_tag: 'Succulent Bachali',
      is_organic: true,
      image_url: '/greens/bachalakura.jpg',
      rating: 4.8,
      review_count: 96,
      is_featured: false,
    },
    {
      id: 55,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Sorrel (Chukakura)',
      tagline: 'Pleasantly sour, juicy green sorrel cooking leaves',
      description: 'Tender tangy leaves providing a refreshing citrusy zest to lentils and leafy stir-fries.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '250g bunch',
      stock_quantity: 45,
      freshness_tag: 'Zesty Green',
      is_organic: true,
      image_url: '/greens/chukakura.jpg',
      rating: 4.7,
      review_count: 84,
      is_featured: false,
    },
    {
      id: 56,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Moringa Leaves',
      tagline: 'Nutrient-dense superfood drumstick leaves packed with vitamins',
      description: 'Ancient Ayurvedic superfood tiny leaves brimming with protein, iron, and powerful antioxidants.',
      price: 35.00,
      original_price: 50.00,
      discount_percentage: 30,
      unit: '200g pack',
      stock_quantity: 55,
      freshness_tag: 'Superfood Munaga',
      is_organic: true,
      image_url: '/greens/munagaku.jpg',
      rating: 4.9,
      review_count: 230,
      is_featured: true,
    },
    {
      id: 57,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Ponnaganti Leaves',
      tagline: 'Traditional cooling herbal water-amaranth greens for wellness',
      description: 'Revered in traditional medicine for eye health and cooling properties. Mild, tender earthy flavor.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '250g bunch',
      stock_quantity: 40,
      freshness_tag: 'Herbal Wellness',
      is_organic: true,
      image_url: '/greens/ponnaganti.jpg',
      rating: 4.8,
      review_count: 112,
      is_featured: false,
    },
    {
      id: 58,
      category: 2,
      category_name: 'Leafy Greens',
      category_slug: 'greens',
      name: 'Spring Onions',
      tagline: 'Crisp green scallion stalks with mild white bulbs',
      description: 'Crunchy hollow green stems with tender pungent bulbs. Ideal for stir-fries, fried rice, and salads.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '250g bunch',
      stock_quantity: 70,
      freshness_tag: 'Crisp Scallions',
      is_organic: true,
      image_url: '/greens/springoninos.jpg',
      rating: 4.8,
      review_count: 175,
      is_featured: false,
    },

    // === Daily Veggies (All 35 items) ===
    {
      id: 59,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Ash Gourd',
      tagline: 'Hydrating, cooling native white pumpkin with mild flavor',
      description: 'Low-calorie, highly cooling winter melon prized in Indian wellness for detox juices and soothing curries.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '1 pc (approx 1 kg)',
      stock_quantity: 40,
      freshness_tag: 'Hydrating Detox',
      is_organic: true,
      image_url: '/veggies/ashgourd.jpg',
      rating: 4.8,
      review_count: 114,
      is_featured: false,
    },
    {
      id: 60,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Beetroot',
      tagline: 'Deep crimson, sweet and earthy antioxidant-packed roots',
      description: 'Crisp and juicy ruby-red beetroots rich in iron, nitrates, and folates. Excellent for juices and salads.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '500g pack',
      stock_quantity: 55,
      freshness_tag: 'Iron Rich',
      is_organic: true,
      image_url: '/veggies/beetroot.jpg',
      rating: 4.8,
      review_count: 230,
      is_featured: false,
    },
    {
      id: 61,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Bitter Gourd (Karela)',
      tagline: 'Crisp, ridged emerald karela revered for blood sugar wellness',
      description: 'Firm, crunchy bitter gourds harvested young for minimal bitterness. Ideal for bharwa karela or crispy fry.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '500g pack',
      stock_quantity: 45,
      freshness_tag: 'Wellness Superfood',
      is_organic: true,
      image_url: '/veggies/bittergourd.jpg',
      rating: 4.7,
      review_count: 168,
      is_featured: false,
    },
    {
      id: 62,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Bottle Gourd (Lauki)',
      tagline: 'Tender, light green lauki with sweet succulent flesh',
      description: 'Cooling, easily digestible gourd packed with water and dietary fiber. Perfect for comforting dals, sabzis, or juice.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '1 pc (approx 800g)',
      stock_quantity: 50,
      freshness_tag: 'Cooling Farm Fresh',
      is_organic: true,
      image_url: '/veggies/bottlegourd.jpg',
      rating: 4.8,
      review_count: 195,
      is_featured: false,
    },
    {
      id: 63,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Broccoli',
      tagline: 'Dense, emerald florets rich in vitamins and sulforaphane',
      description: 'Tender, crunchy broccoli crowns cultivated in cool climate farms. Ideal for steaming, stir-fries, and pasta.',
      price: 75.00,
      original_price: 95.00,
      discount_percentage: 21,
      unit: '1 pc (approx 400g)',
      stock_quantity: 35,
      freshness_tag: 'Super Green',
      is_organic: true,
      image_url: '/veggies/broccoli.jpg',
      rating: 4.9,
      review_count: 260,
      is_featured: true,
    },
    {
      id: 64,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Cabbage',
      tagline: 'Tightly packed, crisp green leaves with sweet crunch',
      description: 'Farm-fresh round green cabbage. Holds crispness well in salads, stir-fries, momos, and traditional poriyals.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '1 pc (approx 600g)',
      stock_quantity: 60,
      freshness_tag: 'Crisp Farm Pick',
      is_organic: true,
      image_url: '/veggies/cabbage.jpg',
      rating: 4.7,
      review_count: 175,
      is_featured: false,
    },
    {
      id: 65,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Carrots',
      tagline: 'Crunchy, naturally sweet vibrant orange table carrots',
      description: 'Clean washed, sweet juicy carrots loaded with Beta-Carotene and Vitamin A. Great for raw snacking or cooking.',
      price: 45.00,
      original_price: 60.00,
      discount_percentage: 25,
      unit: '500g pack',
      stock_quantity: 65,
      freshness_tag: 'Sweet & Crisp',
      is_organic: true,
      image_url: '/veggies/carrot.jpg',
      rating: 4.9,
      review_count: 310,
      is_featured: true,
    },
    {
      id: 66,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Cauliflower',
      tagline: 'Creamy-white, spotless dense curds wrapped in fresh leaves',
      description: 'Compact, crisp cauliflower head. Chemical-free cultivation preserving pure flavor for aloo gobi or roasting.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '1 pc (approx 600g)',
      stock_quantity: 50,
      freshness_tag: 'Farm Harvested',
      is_organic: true,
      image_url: '/veggies/cauliflower.jpg',
      rating: 4.8,
      review_count: 225,
      is_featured: false,
    },
    {
      id: 67,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Cluster Beans (Gawar)',
      tagline: 'Tender, fiber-rich native cluster beans with delicate nutty taste',
      description: 'Crisp green gawar phali harvested young for zero fiber toughness. Classic Indian comfort sabzi staple.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '250g pack',
      stock_quantity: 45,
      freshness_tag: 'High Fiber',
      is_organic: true,
      image_url: '/veggies/clusterbeans.jpg',
      rating: 4.7,
      review_count: 130,
      is_featured: false,
    },
    {
      id: 68,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Fresh Coconut',
      tagline: 'Fresh whole brown coconut with sweet meat and rich water',
      description: 'Freshly de-husked coconut filled with refreshing electrolyte water and thick, creamy white edible kernel.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '1 pc',
      stock_quantity: 75,
      freshness_tag: 'Sweet Kernel',
      is_organic: true,
      image_url: '/veggies/coconut.jpg',
      rating: 4.9,
      review_count: 420,
      is_featured: true,
    },
    {
      id: 69,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Colocasia (Arbi)',
      tagline: 'Nutty, starchy taro root bulbs with earthy richness',
      description: 'Firm brown arbi tubers. High in gut-healthy resistant starch, delicious boiled, spiced, and roasted crispy.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '500g pack',
      stock_quantity: 40,
      freshness_tag: 'Starch Rich',
      is_organic: true,
      image_url: '/veggies/colacasia.jpg',
      rating: 4.7,
      review_count: 118,
      is_featured: false,
    },
    {
      id: 70,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Cucumber (Kheera)',
      tagline: 'Juicy, crisp field-grown Indian salad cucumbers',
      description: 'Ultra-hydrating, refreshing cucumbers with thin skin and tender seeds. Cooling addition to any daily meal.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '500g pack (3-4 pcs)',
      stock_quantity: 70,
      freshness_tag: 'Crisp & Juicy',
      is_organic: true,
      image_url: '/veggies/cucumber.jpg',
      rating: 4.8,
      review_count: 285,
      is_featured: false,
    },
    {
      id: 71,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Drumsticks (Sahjan)',
      tagline: 'Tender, flavorful moringa pods for sambar and curries',
      description: 'Fresh, juicy drumstick pods packed with marrow. Infuses unmistakable fragrant sweetness into dals and gravies.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '250g pack (4-5 pcs)',
      stock_quantity: 50,
      freshness_tag: 'Rich in Minerals',
      is_organic: true,
      image_url: '/veggies/drumstick.jpg',
      rating: 4.8,
      review_count: 190,
      is_featured: false,
    },
    {
      id: 72,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Brinjal (Eggplant)',
      tagline: 'Glossy deep purple tender eggplants with creamy flesh',
      description: 'Tender, spotless baingan. Melts into a velvety texture when roasted for bharta or simmered in curries.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '500g pack (3-4 pcs)',
      stock_quantity: 60,
      freshness_tag: 'Tender Purple',
      is_organic: true,
      image_url: '/veggies/eggplant.jpg',
      rating: 4.8,
      review_count: 215,
      is_featured: false,
    },
    {
      id: 73,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'French Beans',
      tagline: 'Crisp, stringless tender green beans handpicked at dawn',
      description: 'Slender, snap-fresh green beans rich in dietary fiber and folate. Slices effortlessly for quick everyday stir-fries.',
      price: 40.00,
      original_price: 50.00,
      discount_percentage: 20,
      unit: '250g pack',
      stock_quantity: 55,
      freshness_tag: 'Snap Fresh',
      is_organic: true,
      image_url: '/veggies/frenchbeans.jpg',
      rating: 4.8,
      review_count: 180,
      is_featured: false,
    },
    {
      id: 74,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Garlic (Lahsun)',
      tagline: 'Pungent, firm Indian native garlic pods with bold aroma',
      description: 'Tight papery skin enclosing intensely aromatic cloves. Essential for tadka, medicinal immunity, and flavoring.',
      price: 55.00,
      original_price: 75.00,
      discount_percentage: 27,
      unit: '250g pack',
      stock_quantity: 80,
      freshness_tag: 'Aromatic Bulb',
      is_organic: true,
      image_url: '/veggies/garlic.jpg',
      rating: 4.9,
      review_count: 340,
      is_featured: true,
    },
    {
      id: 75,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Ginger (Adrak)',
      tagline: 'Spicy, zesty fresh mountain ginger rhizomes',
      description: 'Juicy, fibrous ginger roots bursting with gingerol and warmth. Indispensable for morning chai, curries, and remedies.',
      price: 45.00,
      original_price: 60.00,
      discount_percentage: 25,
      unit: '250g pack',
      stock_quantity: 75,
      freshness_tag: 'Spicy Warmth',
      is_organic: true,
      image_url: '/veggies/ginger.jpg',
      rating: 4.9,
      review_count: 325,
      is_featured: true,
    },
    {
      id: 76,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Green Capsicum',
      tagline: 'Crunchy, thick-walled fresh green bell peppers',
      description: 'Plump, glossy green capsicums harvested with morning dew. Holds crunch in kadai dishes and tossed salads.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '500g pack (3 pcs)',
      stock_quantity: 55,
      freshness_tag: 'Crisp & Juicy',
      is_organic: true,
      image_url: '/veggies/greencapsicum.jpg',
      rating: 4.8,
      review_count: 195,
      is_featured: false,
    },
    {
      id: 77,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Green Chillies',
      tagline: 'Fiery, aromatic fresh slender green Indian chillies',
      description: 'Vibrant green chillies picked for bold heat and pungent aroma. A must-have seasoning for Indian kitchens.',
      price: 20.00,
      original_price: 28.00,
      discount_percentage: 29,
      unit: '100g pack',
      stock_quantity: 90,
      freshness_tag: 'Fiery Fresh',
      is_organic: true,
      image_url: '/veggies/greenchilis.jpg',
      rating: 4.8,
      review_count: 280,
      is_featured: false,
    },
    {
      id: 78,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Ivy Gourd (Tindora)',
      tagline: 'Crunchy, tender baby tindora with pleasant nutty taste',
      description: 'Firm, striped miniature gourds packed with antioxidants. Crisp and delicious when sautéed with roasted spices.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '250g pack',
      stock_quantity: 45,
      freshness_tag: 'Tender Tindora',
      is_organic: true,
      image_url: '/veggies/ivygourd.jpg',
      rating: 4.7,
      review_count: 140,
      is_featured: false,
    },
    {
      id: 79,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Lemons (Nimbu)',
      tagline: 'Juicy, thin-skinned yellow kagzi lemons loaded with juice',
      description: 'Fragrant and zesty sour citrus bursting with Vitamin C. Perfect for fresh shikanji, seasoning, and marinades.',
      price: 25.00,
      original_price: 35.00,
      discount_percentage: 29,
      unit: '4 pcs pack',
      stock_quantity: 100,
      freshness_tag: 'Zesty Tang',
      is_organic: true,
      image_url: '/veggies/lemons.jpg',
      rating: 4.9,
      review_count: 380,
      is_featured: true,
    },
    {
      id: 80,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Button Mushrooms',
      tagline: 'Spotless, firm and hygienic fresh white button mushrooms',
      description: 'Cultivated in sterile climate humidity. Earthy, umami-rich, packed same day for maximum freshness and texture.',
      price: 60.00,
      original_price: 80.00,
      discount_percentage: 25,
      unit: '200g punnet',
      stock_quantity: 45,
      freshness_tag: 'Packed Same Day',
      is_organic: true,
      image_url: '/veggies/mushrooms.jpg',
      rating: 4.8,
      review_count: 240,
      is_featured: false,
    },
    {
      id: 81,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Lady Finger (Bhindi)',
      tagline: 'Tender, slender green okra with zero fibrous toughness',
      description: 'Hand-sorted baby okra that snaps easily at the tip. Non-sticky when cooked into delicious kurkuri or masala bhindi.',
      price: 35.00,
      original_price: 48.00,
      discount_percentage: 27,
      unit: '500g pack',
      stock_quantity: 65,
      freshness_tag: 'Tender Baby Okra',
      is_organic: true,
      image_url: '/veggies/okra.jpg',
      rating: 4.8,
      review_count: 260,
      is_featured: true,
    },
    {
      id: 82,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Onions (Pyaz)',
      tagline: 'Pungent, firm Indian cooking onions direct from mandi',
      description: 'Essential kitchen backbone with thin papery skin and juicy, flavorful layers. Long lasting and rich in taste.',
      price: 60.00,
      original_price: 80.00,
      discount_percentage: 25,
      unit: '2 kg bag',
      stock_quantity: 100,
      freshness_tag: 'Direct from Mandi',
      is_organic: true,
      image_url: '/veggies/onions.jpg',
      rating: 4.8,
      review_count: 690,
      is_featured: true,
    },
    {
      id: 83,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Green Peas (Matar)',
      tagline: 'Sweet, plump emerald peas harvested from cool hills',
      description: 'Naturally sweet green peas bursting with tenderness. Wonderful in pulav, matar paneer, or enjoyed steamed.',
      price: 50.00,
      original_price: 70.00,
      discount_percentage: 29,
      unit: '500g pack',
      stock_quantity: 60,
      freshness_tag: 'Sweet Green',
      is_organic: true,
      image_url: '/veggies/peas.jpg',
      rating: 4.9,
      review_count: 285,
      is_featured: true,
    },
    {
      id: 84,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Potatoes (Aloo)',
      tagline: 'Clean, thin-skinned everyday cooking potatoes',
      description: 'Smooth, unblemished all-purpose potatoes with firm texture. Ideal for roasting, boiling, parathas, and curries.',
      price: 50.00,
      original_price: 70.00,
      discount_percentage: 29,
      unit: '2 kg bag',
      stock_quantity: 110,
      freshness_tag: 'Farm Dug Fresh',
      is_organic: true,
      image_url: '/veggies/potatoes.jpg',
      rating: 4.8,
      review_count: 560,
      is_featured: true,
    },
    {
      id: 85,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Pumpkin (Kaddu)',
      tagline: 'Golden-orange sweet pumpkin with rich creamy flesh',
      description: 'Naturally sweet winter squash rich in Vitamin A, zinc, and fiber. Superb for comforting soups, sambar, and sabzi.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '1 pc (approx 1 kg)',
      stock_quantity: 40,
      freshness_tag: 'Golden Sweet',
      is_organic: true,
      image_url: '/veggies/pumpkin.jpg',
      rating: 4.7,
      review_count: 150,
      is_featured: false,
    },
    {
      id: 86,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'White Radish (Mooli)',
      tagline: 'Crisp, peppery white radish with vibrant green leaves',
      description: 'Clean white crunchy root with pleasant peppery bite. Great for digestion, mooli parathas, and fresh winter salads.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '500g pack (2-3 pcs)',
      stock_quantity: 50,
      freshness_tag: 'Crunchy Peppery',
      is_organic: true,
      image_url: '/veggies/radish.jpg',
      rating: 4.7,
      review_count: 160,
      is_featured: false,
    },
    {
      id: 87,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Raw Banana (Plantain)',
      tagline: 'Firm green cooking bananas rich in prebiotic starch',
      description: 'Dense, firm plantains traditional in South Indian cooking for chips, thoran, curries, and crispy roasts.',
      price: 30.00,
      original_price: 40.00,
      discount_percentage: 25,
      unit: '3 pcs pack',
      stock_quantity: 55,
      freshness_tag: 'Cooking Plantain',
      is_organic: true,
      image_url: '/veggies/rawbanana.jpg',
      rating: 4.8,
      review_count: 175,
      is_featured: false,
    },
    {
      id: 88,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Raw Mango (Kaccha Aam)',
      tagline: 'Tangy, firm sour raw green mangoes for chutneys',
      description: 'Puckery sour green mango with crunchy white flesh. Essential for aam panna, spicy pickles, and summer dals.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '500g pack (2 pcs)',
      stock_quantity: 45,
      freshness_tag: 'Tangy Sour',
      is_organic: true,
      image_url: '/veggies/rawmango.jpg',
      rating: 4.9,
      review_count: 210,
      is_featured: false,
    },
    {
      id: 89,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Red Capsicum',
      tagline: 'Sweet, vibrant ruby-red bell peppers packed with Vitamin C',
      description: 'Sun-ripened red capsicums with thick juicy walls and gentle natural sweetness. Elevates pasta, grills, and salads.',
      price: 65.00,
      original_price: 85.00,
      discount_percentage: 24,
      unit: '2 pcs (approx 350g)',
      stock_quantity: 40,
      freshness_tag: 'Sweet Ruby',
      is_organic: true,
      image_url: '/veggies/redcapcicum.jpg',
      rating: 4.8,
      review_count: 185,
      is_featured: false,
    },
    {
      id: 90,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Ridge Gourd (Turai)',
      tagline: 'Tender, cooling ridged gourd with sweet soft flesh',
      description: 'Mild and delicate vegetable high in dietary water and low in calories. Highly comforting in everyday home cooking.',
      price: 35.00,
      original_price: 45.00,
      discount_percentage: 22,
      unit: '500g pack (2-3 pcs)',
      stock_quantity: 50,
      freshness_tag: 'Cooling Turai',
      is_organic: true,
      image_url: '/veggies/ridgegourd.jpg',
      rating: 4.7,
      review_count: 135,
      is_featured: false,
    },
    {
      id: 91,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Sweet Corn',
      tagline: 'Golden, milky sweet corn cobs with tender kernels',
      description: 'Plump yellow corn cobs bursting with juicy natural sweetness. Delicious boiled with butter and chaat masala.',
      price: 35.00,
      original_price: 50.00,
      discount_percentage: 30,
      unit: '2 pcs pack',
      stock_quantity: 65,
      freshness_tag: 'Milky Sweet',
      is_organic: true,
      image_url: '/veggies/sweetcorn.jpg',
      rating: 4.9,
      review_count: 290,
      is_featured: true,
    },
    {
      id: 92,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Sweet Potatoes (Shakarkandi)',
      tagline: 'Caramel-rich purple-skin sweet potatoes packed with energy',
      description: 'Naturally sweet starchy tubers high in fiber and beta-carotene. Irresistible roasted with lemon juice and chaat masala.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '500g pack',
      stock_quantity: 50,
      freshness_tag: 'Slow Energy',
      is_organic: true,
      image_url: '/veggies/sweetpotatoes.jpg',
      rating: 4.8,
      review_count: 195,
      is_featured: false,
    },
    {
      id: 93,
      category: 3,
      category_name: 'Daily Veggies',
      category_slug: 'veggies',
      name: 'Tomatoes (Tamatar)',
      tagline: 'Firm, juicy red ripe country tomatoes with balanced tang',
      description: 'Vine-ripened local desi tomatoes boasting sweet-tart acidity and thick pulp. The indispensable heart of Indian cooking.',
      price: 40.00,
      original_price: 55.00,
      discount_percentage: 27,
      unit: '1 kg pack',
      stock_quantity: 100,
      freshness_tag: 'Vine Ripened',
      is_organic: true,
      image_url: '/veggies/tomatoes.jpg',
      rating: 4.9,
      review_count: 640,
      is_featured: true,
    }
  ];

  private getAuthHeaders(): HttpHeaders {
    const token = typeof window !== 'undefined' ? localStorage.getItem('freshcart_token') : null;
    let headers = new HttpHeaders();
    if (token) {
      headers = headers.set('Authorization', `Token ${token}`);
    }
    return headers;
  }

  /**
   * Fetch categories from Django API with fallback
   */
  getCategories(): Observable<Category[]> {
    return this.http.get<any>(`${this.baseUrl}/categories/`).pipe(
      map(res => {
        if (Array.isArray(res)) return res;
        if (res && Array.isArray(res.results)) return res.results;
        return this.fallbackCategories;
      }),
      catchError(() => of(this.fallbackCategories))
    );
  }

  /**
   * Fetch products from Django API with optional category and search query.
   * Core Rule: Unauthenticated visitors cannot access or load products.
   */
  getProducts(categorySlug?: string, search?: string): Observable<Product[]> {
    const token = typeof window !== 'undefined' ? localStorage.getItem('freshcart_token') : null;
    if (!token) {
      // Unauthenticated visitor cannot view products!
      return of([]);
    }

    let params = new HttpParams();
    if (categorySlug && categorySlug !== 'all') {
      params = params.set('category', categorySlug);
    }
    if (search && search.trim()) {
      params = params.set('search', search.trim());
    }

    const headers = this.getAuthHeaders();

    return this.http.get<any>(`${this.baseUrl}/products/`, { params, headers }).pipe(
      map(res => {
        let items: Product[] = [];
        if (Array.isArray(res)) {
          items = res;
        } else if (res && Array.isArray(res.results)) {
          items = res.results;
        } else {
          items = this.fallbackProducts;
        }
        const custom = this.getCustomProducts();
        const merged = [...custom, ...items.filter(it => !custom.some(c => c.id === it.id))];
        return this.normalizeProducts(merged);
      }),
      catchError(err => {
        if (err?.status === 401) {
          return of([]);
        }
        // Filter fallback data client-side if API server is temporarily offline but user is logged in
        const custom = this.getCustomProducts();
        let filtered = [...custom, ...this.fallbackProducts.filter(it => !custom.some(c => c.id === it.id))];
        if (categorySlug && categorySlug !== 'all') {
          filtered = filtered.filter(p => p.category_slug === categorySlug);
        }
        if (search && search.trim()) {
          const q = search.toLowerCase().trim();
          filtered = filtered.filter(p =>
            p.name.toLowerCase().includes(q) ||
            (p.category_name && p.category_name.toLowerCase().includes(q)) ||
            (p.category_slug && p.category_slug.toLowerCase().includes(q)) ||
            (p.tagline && p.tagline.toLowerCase().includes(q)) ||
            (p.freshness_tag && p.freshness_tag.toLowerCase().includes(q))
          );
        }
        return of(this.normalizeProducts(filtered));
      })
    );
  }

  /**
   * Submit an order to the Django backend
   */
  createOrder(orderData: OrderRequest): Observable<OrderResponse> {
    const headers = this.getAuthHeaders();
    return this.http.post<OrderResponse>(`${this.baseUrl}/orders/`, orderData, { headers }).pipe(
      catchError(err => {
        // If API is unreachable, generate a seamless offline confirmation response
        const randomId = Math.floor(100000 + Math.random() * 900000);
        const subtotal = orderData.order_items.reduce((acc, item) => {
          const prod = this.fallbackProducts.find(p => p.id === item.product_id);
          const price = prod ? Number(prod.price) : 50;
          return acc + price * item.quantity;
        }, 0);
        const deliveryFee = subtotal >= 299 ? 0 : 40;
        const total = subtotal + deliveryFee;

        const simulatedResponse: OrderResponse = {
          id: randomId,
          order_number: `FC-2026-${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
          customer_name: orderData.customer_name,
          customer_phone: orderData.customer_phone,
          customer_email: orderData.customer_email,
          delivery_address: orderData.delivery_address,
          delivery_slot: orderData.delivery_slot,
          subtotal: subtotal.toFixed(2),
          delivery_fee: deliveryFee.toFixed(2),
          total_amount: total.toFixed(2),
          payment_method: orderData.payment_method,
          status: 'CONFIRMED',
          notes: orderData.notes,
          created_at: new Date().toISOString(),
          items: orderData.order_items.map((item, idx) => {
            const prod = this.fallbackProducts.find(p => p.id === item.product_id);
            const price = prod ? Number(prod.price) : 50;
            return {
              id: idx + 1,
              product: item.product_id,
              product_name: prod ? prod.name : `Produce #${item.product_id}`,
              product_unit: prod ? prod.unit : '1 kg',
              price: price.toFixed(2),
              quantity: item.quantity,
              item_total: (price * item.quantity).toFixed(2)
            };
          })
        };
        return of(simulatedResponse);
      })
    );
  }

  private getCustomProducts(): Product[] {
    if (typeof window === 'undefined') return [];
    try {
      const data = localStorage.getItem('freshcart_custom_products');
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  }

  private saveCustomProducts(products: Product[]): void {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem('freshcart_custom_products', JSON.stringify(products));
    } catch (e) {
      console.error('Failed to save custom products', e);
    }
  }

  /**
   * Admin API: Add new produce item to the store
   */
  createProduct(productData: Partial<Product>): Observable<Product> {
    const headers = this.getAuthHeaders();
    return this.http.post<Product>(`${this.baseUrl}/products/`, productData, { headers }).pipe(
      map(created => {
        const custom = this.getCustomProducts();
        const normalized = this.normalizeProducts([created])[0];
        this.saveCustomProducts([normalized, ...custom]);
        return normalized;
      }),
      catchError(() => {
        // Fallback for immediate offline persistence
        const id = Math.floor(10000 + Math.random() * 90000);
        const catId = Number(productData.category) || 1;
        const newProd: Product = {
          id,
          category: catId,
          category_name: catId === 2 ? 'Leafy Greens' : catId === 3 ? 'Daily Veggies' : 'Fresh Fruits',
          category_slug: catId === 2 ? 'greens' : catId === 3 ? 'veggies' : 'fruits',
          name: productData.name || 'Farm-Fresh Produce',
          tagline: productData.tagline || 'Direct from organic farmers',
          description: productData.description || 'Grown sustainably and harvested at dawn for ultimate farm freshness.',
          price: Number(productData.price) || 120,
          original_price: productData.original_price ? Number(productData.original_price) : null,
          discount_percentage: productData.original_price && Number(productData.original_price) > Number(productData.price)
            ? Math.round(((Number(productData.original_price) - Number(productData.price)) / Number(productData.original_price)) * 100)
            : 0,
          unit: productData.unit || '1 kg',
          stock_quantity: Number(productData.stock_quantity) || 50,
          freshness_tag: productData.freshness_tag || 'Fresh Harvest',
          is_organic: productData.is_organic ?? true,
          image_url: productData.image_url || '/fruits/apples.jpg',
          rating: 4.9,
          review_count: 14,
          is_featured: productData.is_featured ?? true,
        };
        const custom = this.getCustomProducts();
        this.saveCustomProducts([newProd, ...custom]);
        return of(newProd);
      })
    );
  }

  /**
   * Admin API: Update existing produce item
   */
  updateProduct(id: number, productData: Partial<Product>): Observable<Product> {
    const headers = this.getAuthHeaders();
    return this.http.patch<Product>(`${this.baseUrl}/products/${id}/`, productData, { headers }).pipe(
      map(updated => {
        let custom = this.getCustomProducts();
        custom = custom.map(p => p.id === id ? { ...p, ...updated } : p);
        this.saveCustomProducts(custom);
        return this.normalizeProducts([updated])[0];
      }),
      catchError(() => {
        let custom = this.getCustomProducts();
        const existing = custom.find(p => p.id === id) || this.fallbackProducts.find(p => p.id === id);
        if (existing) {
          const updated = { ...existing, ...productData } as Product;
          custom = [updated, ...custom.filter(p => p.id !== id)];
          this.saveCustomProducts(custom);
          return of(updated);
        }
        return of(productData as Product);
      })
    );
  }

  /**
   * Admin API: Delete a product
   */
  deleteProduct(id: number): Observable<boolean> {
    const headers = this.getAuthHeaders();
    return this.http.delete(`${this.baseUrl}/products/${id}/`, { headers }).pipe(
      map(() => {
        let custom = this.getCustomProducts().filter(p => p.id !== id);
        this.saveCustomProducts(custom);
        return true;
      }),
      catchError(() => {
        let custom = this.getCustomProducts().filter(p => p.id !== id);
        this.saveCustomProducts(custom);
        return of(true);
      })
    );
  }

  /**
   * Admin API: Get all customer orders
   */
  getAllOrders(): Observable<OrderResponse[]> {
    const headers = this.getAuthHeaders();
    return this.http.get<any>(`${this.baseUrl}/orders/`, { headers }).pipe(
      map(res => {
        if (Array.isArray(res)) return res;
        if (res && Array.isArray(res.results)) return res.results;
        return [];
      }),
      catchError(() => {
        return of([
          {
            id: 101,
            order_number: 'FC-2026-A8K9L2',
            customer_name: 'Priya Sharma',
            customer_phone: '+91 98765 43210',
            customer_email: 'priya.sharma@gmail.com',
            delivery_address: '402, Green Glen Layout, Bellandur, Bengaluru 560103',
            delivery_slot: 'Express Delivery: Within 2 Hours',
            subtotal: '445.00',
            delivery_fee: '0.00',
            total_amount: '445.00',
            payment_method: 'UPI',
            status: 'CONFIRMED',
            notes: 'Leave at security gate please',
            created_at: new Date().toISOString(),
            items: [
              { id: 1, product: 1, product_name: 'Apples', product_unit: '1 kg (4-5 pcs)', price: '180.00', quantity: 2, item_total: '360.00' },
              { id: 2, product: 47, product_name: 'Baby Spinach (Palak)', product_unit: '250g bunch', price: '45.00', quantity: 1, item_total: '45.00' }
            ]
          }
        ]);
      })
    );
  }

  private normalizeProducts(products: Product[]): Product[] {
    return products.map(p => ({
      ...p,
      price: Number(p.price),
      original_price: p.original_price ? Number(p.original_price) : null,
      rating: Number(p.rating),
      discount_percentage: p.discount_percentage ?? (p.original_price && Number(p.original_price) > Number(p.price)
        ? Math.round(((Number(p.original_price) - Number(p.price)) / Number(p.original_price)) * 100)
        : 0)
    }));
  }
}
